import { test, expect } from '@playwright/test'
import { ALL_TOURS } from '../../../src/features/tour/registry'
import { setupDashboard, startTour, openHelp, assertBounds, projectId } from './fixtures'

test('escribir, abrir formularios y cerrar no completar una guía', async ({ page }, info) => {
  const { errors } = await setupDashboard(page)
  await page.goto('/dashboard?tab=collab')
  await startTour(page, 'Misión 1: Exploración del Tablero Kanban')
  const guide = page.getByTestId('tour-guide')
  const search = page.locator('[data-tour="collab-search"]').locator('input').or(page.locator('input[data-tour="collab-search"]')).first()
  await search.fill('Texto sin resultados')
  await search.press('Enter')
  await expect(search).toBeFocused()
  await expect(guide).toContainText('Paso 1 de 5')
  await assertBounds(page)
  await guide.getByRole('button', { name: 'Minimizar tutorial' }).click()
  await expect(guide.getByRole('heading')).toHaveCount(0)
  await guide.getByRole('button', { name: 'Expandir tutorial' }).click()
  await search.fill('')
  for (let step = 2; step <= 4; step++) {
    await guide.getByRole('button', { name: 'Siguiente', exact: true }).click()
    await expect(guide).toContainText(`Paso ${step} de 5`)
    await expect(guide).toHaveAttribute('aria-busy', 'false')
  }
  await page.locator('[data-tour="collab-create-btn"]').click()
  const form = page.getByRole('dialog').filter({ hasNot: page.getByText('Centro de ayuda', { exact: true }) })
  await expect(form).toBeVisible()
  await expect(guide).toHaveCount(0)
  await form.getByRole('button', { name: /cerrar|cancelar/i }).first().click()
  await expect(guide).toContainText('Paso 4 de 5')
  await assertBounds(page)
  await page.screenshot({ path: info.outputPath('hybrid.png'), fullPage: true })
  await guide.getByRole('button', { name: 'Cerrar tutorial' }).click()
  expect(await page.evaluate(() => JSON.parse(localStorage.getItem('cima_tour_v2:tutorial%40example.com') ?? '[]'))).toEqual([])
  expect(errors).toEqual([])
})

test('buscar desde otra sección y cambiar subpestañas conservadas de Marketing', async ({ page }, info) => {
  const { errors, mutations } = await setupDashboard(page, 'worker')
  await page.goto('/dashboard?tab=collab')
  await openHelp(page)
  await page.getByRole('button', { name: 'Todas las guías', exact: true }).click()
  await page.getByLabel('Buscar guías y acciones').fill('campaña publicitaria')
  await page.getByRole('button', { name: /¿Cómo creo una nueva campaña publicitaria/ }).click()
  await expect(page).toHaveURL(/tab=marketing/)
  const guide = page.getByTestId('tour-guide')
  await expect(guide).toHaveAttribute('aria-busy', 'false')
  await expect(page.locator('[data-tour="marketing-new-campaign-btn"]')).toBeVisible()
  await assertBounds(page)
  await guide.getByRole('button', { name: 'Cerrar tutorial' }).click()
  await startTour(page, 'Recorrido del Módulo de Marketing')
  for (let index = 0; index < 8; index++) {
    await expect(guide).toHaveAttribute('aria-busy', 'false')
    await expect(guide).toContainText(`Paso ${index + 1} de 8`)
    await expect(guide).not.toContainText('Este elemento no está disponible')
    await assertBounds(page)
    if (index === 5) {
      await page.locator('[data-tour="marketing-tab-proposals"]').click()
      await expect(guide.getByRole('button', { name: 'Volver al paso' })).toBeVisible()
      await guide.getByRole('button', { name: 'Volver al paso' }).click()
      await expect(page.locator('[data-tour="marketing-campaigns-filters"]')).toBeVisible()
    }
    await guide.getByRole('button', { name: index === 7 ? 'Finalizar' : 'Siguiente', exact: true }).click()
  }
  await openHelp(page)
  await page.screenshot({ path: info.outputPath('help-center.png'), fullPage: true })
  await expect(page.getByRole('dialog')).toContainText('Completado')
  await page.reload()
  await openHelp(page)
  await expect(page.getByRole('dialog')).toContainText('Completado')
  expect(errors).toEqual([])
  expect(mutations).toEqual([])
})

test('proyecto abierto por el usuario, retroceso y tab dinámico', async ({ page }, info) => {
  const { errors } = await setupDashboard(page, 'worker')
  await page.goto('/dashboard?tab=collab')
  await startTour(page, 'Recorrido del Tablero y Proyectos')
  const guide = page.getByTestId('tour-guide')
  for (let index = 1; index < 4; index++) {
    await guide.getByRole('button', { name: 'Siguiente', exact: true }).click()
    await expect(guide).toHaveAttribute('aria-busy', 'false')
  }
  await page.getByRole('button', { name: /Abrir proyecto Proyecto de prueba/ }).click()
  await expect(page).toHaveURL(new RegExp(projectId))
  await expect(guide).toContainText('Paso 4')
  await guide.getByRole('button', { name: /Siguiente|Omitir paso/ }).click()
  await expect(guide.getByRole('heading')).toHaveText('Informacion del Proyecto')
  await expect(guide).toHaveAttribute('aria-busy', 'false')
  await assertBounds(page)
  await guide.getByRole('button', { name: 'Anterior', exact: true }).click()
  await expect(page).not.toHaveURL(new RegExp(projectId))
  await expect(page.locator('[data-tour="collab-card-first"]')).toBeVisible()
  await guide.getByRole('button', { name: 'Siguiente', exact: true }).click()
  await expect(page).toHaveURL(new RegExp(projectId))
  await expect(guide).toHaveAttribute('aria-busy', 'false')
  await page.screenshot({ path: info.outputPath('workspace.png'), fullPage: true })
  expect(errors).toEqual([])
})

test('vacíos, reintento, ayuda superpuesta, rotación y modo oscuro', async ({ page }, info) => {
  const { errors } = await setupDashboard(page, 'client', true)
  await page.goto('/dashboard?tab=collab')
  await startTour(page, 'Misión 2: Flujo de Tareas Operativas')
  const guide = page.getByTestId('tour-guide')
  await expect(guide.getByRole('button', { name: 'Volver al paso' })).toBeVisible()
  await assertBounds(page)
  await guide.getByRole('button', { name: 'Volver al paso' }).click()
  await guide.getByRole('button', { name: 'Cerrar tutorial' }).click()
  await expect(guide).toHaveCount(0)
  await startTour(page, 'Misión 1: Exploración del Tablero Kanban')
  await openHelp(page)
  await expect(guide).toHaveCount(0)
  await page.getByRole('dialog').getByRole('button', { name: 'Cerrar', exact: true }).click()
  await expect(guide).toContainText('Paso 1')
  await page.evaluate(() => document.documentElement.classList.add('dark'))
  const size = page.viewportSize()!
  await page.setViewportSize({ width: size.height, height: size.width })
  await assertBounds(page)
  await page.screenshot({ path: info.outputPath('rotated-dark.png'), fullPage: true })
  expect(errors).toEqual([])
})

for (const role of ['admin', 'worker', 'client'] as const) {
  for (const tour of ALL_TOURS.filter((tour) => tour.roles.includes(role))) {
    test(`recorrer guía autorizada y finalizar explícitamente: ${role} / ${tour.id}`, async ({ page }, info) => {
      const { errors, mutations } = await setupDashboard(page, role)
      const unavailable: string[] = []
      await page.goto('/dashboard?tab=collab')
      await startTour(page, tour.title)
      const guide = page.getByTestId('tour-guide')
      const steps = tour.steps.filter((step) => !step.requiredRole || step.requiredRole.includes(role))
      for (let index = 0; index < steps.length; index++) {
        await expect(guide).toHaveAttribute('aria-busy', 'false')
        await expect(guide.getByRole('heading')).toHaveText(steps[index].title)
        if (await guide.getByRole('button', { name: 'Volver al paso' }).isVisible()) unavailable.push(steps[index].element)
        await assertBounds(page)
        await guide.getByRole('button', { name: index === steps.length - 1 ? 'Finalizar' : /Siguiente|Omitir paso/, exact: true }).click()
      }
      await expect(guide).toHaveCount(0)
      expect(errors).toEqual([])
      await info.attach('unavailable-targets', { body: JSON.stringify([...new Set(unavailable)], null, 2), contentType: 'application/json' })
      const conditionalTargets = [
        '[data-tour="admin-file-project-header"]', '[data-tour="admin-file-folder-tabs"]',
        '[data-tour="admin-file-table"]', '[data-tour="admin-user-actions"]',
        '[data-tour="account-sessions-revoke-btn"]',
        '[data-tour="workspace-files-panel"]', '[data-tour="workspace-timeline-panel"]',
      ]
      expect([...new Set(unavailable)].filter((selector) => !conditionalTargets.includes(selector))).toEqual([])
      expect(mutations.filter((request) => !request.endsWith('/read'))).toEqual([])
    })
  }
}

test('zoom, teclado, pantalla reducida y reinicio sin trabajo asíncrono residual', async ({ page }, info) => {
  const { errors } = await setupDashboard(page, 'worker')
  await page.addInitScript(() => localStorage.setItem('cima_ui_zoom', '1.5'))
  await page.goto('/dashboard?tab=collab')
  await startTour(page, 'Misión 1: Exploración del Tablero Kanban')
  const guide = page.getByTestId('tour-guide')
  await assertBounds(page)
  await page.setViewportSize({ width: Math.min(page.viewportSize()!.width, 768), height: 420 })
  await assertBounds(page)
  await page.screenshot({ path: info.outputPath('short-viewport-zoom.png'), fullPage: true })
  await page.setViewportSize({ width: 390, height: 260 })
  await expect(guide.getByRole('heading')).toHaveCount(0)
  await expect(guide).toContainText('Paso 1 de 4')
  await assertBounds(page)
  await page.setViewportSize({ width: 390, height: 420 })
  await expect(guide.getByRole('heading')).toHaveText('Buscador de Proyectos')
  await guide.getByRole('button', { name: 'Mostrar elemento', exact: true }).click()
  await expect.poll(() => page.locator('.cima-tour-highlight').evaluate((element) => element.getBoundingClientRect().height > 0)).toBe(true)
  await page.keyboard.press('Escape')
  await expect(guide).toHaveCount(0)
  await startTour(page, 'Misión 2: Flujo de Tareas Operativas')
  await guide.getByRole('button', { name: 'Cerrar tutorial' }).click()
  await startTour(page, 'Recorrido del Centro de Notificaciones')
  await expect(guide.getByRole('heading')).toHaveText('Bandeja de Novedades')
  await page.waitForURL(/tab=notifications/)
  await expect(guide).toHaveAttribute('aria-busy', 'false')
  await guide.getByRole('button', { name: 'Siguiente', exact: true }).click()
  await expect(guide.getByRole('heading')).toHaveText('Actualizar Notificaciones')
  await expect(guide).toHaveAttribute('aria-busy', 'false')
  await page.evaluate(() => window.dispatchEvent(new Event('resize')))
  await expect(guide.getByRole('heading')).toHaveText('Actualizar Notificaciones')
  expect(errors).toEqual([])
})

test('ayuda global permite operar controles fijos y navegación móvil', async ({ page }, info) => {
  const { errors } = await setupDashboard(page, 'worker')
  await page.goto('/dashboard?tab=collab')
  await openHelp(page)
  await page.getByLabel('Buscar guías y acciones').fill('tamaño de letra')
  await page.getByRole('button', { name: /¿Cómo cambio el tamaño de letra/ }).click()
  const guide = page.getByTestId('tour-guide')
  await expect(guide).toHaveAttribute('aria-busy', 'false')
  await page.getByTestId('zoom-widget-trigger').click()
  await page.getByTestId('zoom-in-btn').click()
  await expect(page.getByTestId('zoom-widget-toolbar')).toBeVisible()
  await assertBounds(page)
  await page.screenshot({ path: info.outputPath('global-zoom.png'), fullPage: true })
  await guide.getByRole('button', { name: 'Entendido', exact: true }).click()
  await openHelp(page)
  await page.getByLabel('Buscar guías y acciones').fill('navego')
  await page.getByRole('button', { name: /¿Cómo navego entre las diferentes/ }).click()
  await expect(guide).toHaveAttribute('aria-busy', 'false')
  const mobileMenuTrigger = page.getByRole('button', { name: 'Abrir menu' })
  if (await mobileMenuTrigger.isVisible()) {
    await mobileMenuTrigger.click()
  }
  const navigation = page.getByRole('navigation', { name: 'Navegacion principal' })
  const marketingBtn = navigation.getByRole('button', { name: 'Marketing', exact: true })
  await expect(marketingBtn).toBeVisible()
  await marketingBtn.click({ force: true })
  await expect(page).toHaveURL(/tab=marketing/)
  await assertBounds(page)
  expect(errors).toEqual([])
})
