import type { CimaTourDefinition, GuidedQuestion } from '../model/types'

export const accountTour: CimaTourDefinition = {
  id: 'tour-account',
  tab: 'account',
  title: 'Recorrido de Mi Cuenta',
  description: 'Gestiona tus datos de acceso, foto de perfil, sesiones abiertas y credenciales de seguridad.',
  roles: ['admin', 'worker', 'client'],
  steps: [
    {
      element: '[data-tour="account-header"]',
      title: 'Ajustes de Mi Cuenta',
      description: 'Centro de configuración personal para gestionar tu perfil, dispositivos conectados y credenciales de acceso.',
      actionHint: 'Disponible para todos los miembros de CIMA: administradores, colaboradores y clientes.',
      side: 'bottom',
      align: 'start',
      showPointer: true,
    },
    {
      element: '[data-tour="account-hero"]',
      title: 'Identidad Visual y Perfil',
      description: 'Banner institucional y presentación oficial con tu nombre, correo institucional y credencial de rol.',
      actionHint: 'Verifica tu nivel de acceso asignado en la insignia superior.',
      side: 'bottom',
      align: 'start',
      showPointer: true,
    },
    {
      element: '[data-tour="account-avatar-btn"]',
      fallbackElement: '[data-tour="account-hero"]',
      title: 'Fotografía Oficial y Recorte',
      description: 'Carga una fotografía nítida, recórtala con zoom o visualízala en alta definición para tus proyectos.',
      actionHint: 'Haz clic en el icono de cámara para abrir el menú de opciones fotográficas.',
      side: 'bottom',
      align: 'start',
      showPointer: true,
    },
    {
      element: '[data-tour="account-profile-details"]',
      fallbackElement: '[data-tour="account-hero"]',
      title: 'Detalles de Perfil y Rol',
      description: 'Presenta tu información según tu rol: profesión para colaboradores, o empresa para clientes, más estado de correo.',
      actionHint: 'Si tu correo no está verificado, puedes solicitar el enlace de confirmación aquí.',
      side: 'top',
      align: 'start',
      showPointer: true,
    },
    {
      element: '[data-tour="account-sessions"]',
      title: 'Dispositivos y Sesiones Activas',
      description: 'Audita los navegadores y equipos con sesiones iniciadas para detectar cualquier acceso inusual o no autorizado.',
      actionHint: 'Consulta la fecha, navegador y estado de conexión de cada sesión.',
      side: 'top',
      align: 'start',
      showPointer: true,
    },
    {
      element: '[data-tour="account-sessions-revoke-btn"]',
      fallbackElement: '[data-tour="account-sessions"]',
      title: 'Cierre Remoto Preventivo',
      description: 'Revoca instantáneamente todas las sesiones en otros dispositivos si extraviaste un equipo o sospechas intrusión.',
      actionHint: 'Tu sesión actual permanecerá activa para que no pierdas tu trabajo.',
      side: 'top',
      align: 'end',
      showPointer: true,
    },
    {
      element: '[data-tour="account-security"]',
      title: 'Seguridad y Política de Contraseñas',
      description: 'Protección criptográfica para tu cuenta. Exige mínimo 8 caracteres con mayúsculas, minúsculas, números y símbolos.',
      actionHint: 'Actualizar tu clave cerrará automáticamente las sesiones en otros equipos por seguridad.',
      side: 'top',
      align: 'start',
      showPointer: true,
    },
    {
      element: '[data-tour="account-password-form"]',
      fallbackElement: '[data-tour="account-security"]',
      title: 'Formulario de Cambio de Clave',
      description: 'Ingresa tu contraseña actual y define la nueva contraseña con su respectiva confirmación para validar el cambio.',
      actionHint: 'Completa los tres campos y presiona Actualizar contraseña.',
      side: 'top',
      align: 'start',
      showPointer: true,
    },
  ],
}

export const accountQuestions: GuidedQuestion[] = [
  {
    id: 'acc-q1',
    question: '¿Cómo cambio mi contraseña de acceso?',
    answer: 'En la sección Seguridad de Mi Cuenta, escribe tu clave actual, define la nueva contraseña (mínimo 8 caracteres) y confirma.',
    tab: 'account',
    roles: ['admin', 'worker', 'client'],
    category: 'configuracion',
    targetElement: '[data-tour="account-password-form"]',
    fallbackTargetElement: '[data-tour="account-security"]',
  },
  {
    id: 'acc-q2',
    question: '¿Dónde puedo actualizar o recortar mi foto de perfil?',
    answer: 'En la cabecera de perfil, pulsa sobre la foto o el icono de cámara para subir un archivo, recortarlo con zoom o ver la foto actual.',
    tab: 'account',
    roles: ['admin', 'worker', 'client'],
    category: 'gestion',
    targetElement: '[data-tour="account-avatar-btn"]',
    fallbackTargetElement: '[data-tour="account-hero"]',
  },
  {
    id: 'acc-q3',
    question: '¿Cómo cierro sesiones activas en otros dispositivos?',
    answer: 'En el panel Sesiones Activas, haz clic en "Cerrar sesión en todos los dispositivos" para revocar accesos en otros equipos.',
    tab: 'account',
    roles: ['admin', 'worker', 'client'],
    category: 'configuracion',
    targetElement: '[data-tour="account-sessions-revoke-btn"]',
    fallbackTargetElement: '[data-tour="account-sessions"]',
  },
  {
    id: 'acc-q4',
    question: '¿Cómo verifico mi correo electrónico institucional?',
    answer: 'En la tarjeta de Detalles de Perfil, si tu correo aparece pendiente de verificación, pulsa el botón para recibir el enlace seguro.',
    tab: 'account',
    roles: ['admin', 'worker', 'client'],
    category: 'gestion',
    targetElement: '[data-tour="account-profile-details"]',
    fallbackTargetElement: '[data-tour="account-hero"]',
  },
  {
    id: 'acc-q5',
    question: '¿Qué información de mi perfil varía según mi rol de usuario?',
    answer: 'Los trabajadores visualizan su profesión y proyectos asignados; los clientes visualizan su empresa y tipo de cliente registrado.',
    tab: 'account',
    roles: ['admin', 'worker', 'client'],
    category: 'gestion',
    targetElement: '[data-tour="account-profile-details"]',
    fallbackTargetElement: '[data-tour="account-hero"]',
  },
  {
    id: 'acc-q6',
    question: '¿Qué requisitos debe cumplir mi nueva contraseña?',
    answer: 'Debe contener al menos 8 caracteres combinando letras mayúsculas, minúsculas, al menos un número y un carácter especial.',
    tab: 'account',
    roles: ['admin', 'worker', 'client'],
    category: 'configuracion',
    targetElement: '[data-tour="account-security"]',
  },
]
