import type { CimaTourDefinition, GuidedQuestion } from '../model/types'

export const analyticsTour: CimaTourDefinition = {
  id: 'tour-analytics',
  tab: 'analytics',
  title: 'Recorrido de la Pestaña Analítica',
  description: 'Explora gráficos de rendimiento, volumen de tareas resueltas, KPIs y alertas de inventario.',
  roles: ['admin', 'worker'],
  steps: [
    {
      element: '[data-tour="analytics-header"]',
      title: 'Consola de Analítica',
      description: 'Supervisa métricas de negocio, indicadores clave en tiempo real y el estado del backend analítico.',
      actionHint: 'Pulsa Actualizar para refrescar todos los datos consolidados.',
      side: 'bottom',
      align: 'start',
      showPointer: true,
    },
    {
      element: '[data-tour="analytics-refresh-btn"]',
      fallbackElement: '[data-tour="analytics-header"]',
      title: 'Actualización en Tiempo Real',
      description: 'Refresca todos los indicadores, alertas de inventario y estado de campañas con un solo clic.',
      actionHint: 'Pulsa Actualizar si necesitas los datos más recientes.',
      side: 'bottom',
      align: 'end',
      showPointer: true,
    },
    {
      element: '[data-tour="analytics-charts"]',
      title: 'Panel y Gráficos de KPIs',
      description: 'Visualiza la evolución temporal de proyectos, cumplimiento de objetivos y métricas históricas calculadas.',
      actionHint: 'Examina las tendencias para identificar áreas de oportunidad operativa.',
      side: 'bottom',
      align: 'center',
      showPointer: true,
    },
    {
      element: '[data-tour="analytics-kpis"]',
      title: 'Tarjetas de Desempeño Consolidado',
      description: 'Métricas detalladas de clientes totales, campañas activas, proyectos en curso e interacciones de marketing.',
      actionHint: 'Comprueba el recuento global y usuarios internos asignados.',
      side: 'top',
      align: 'start',
      showPointer: true,
    },
    {
      element: '[data-tour="analytics-campaign-chart"]',
      fallbackElement: '[data-tour="analytics-kpis"]',
      title: 'Estado de Campañas y Exportación',
      description: 'Distribución porcentual de campañas por estado con descarga de datos en formatos ejecutivos.',
      actionHint: 'Exporta los datos para presentaciones y auditoría externa.',
      side: 'top',
      align: 'start',
      showPointer: true,
    },
    {
      element: '[data-tour="analytics-inventory-alerts"]',
      title: 'Alertas de Inventario y Stock',
      description: 'Monitorea productos con existencias bajas y exporta informes ejecutivos en formatos CSV o Excel.',
      actionHint: 'Permite exportar los datos con un solo clic para auditoría comercial.',
      side: 'top',
      align: 'start',
      showPointer: true,
    },
  ],
}

export const analyticsQuestions: GuidedQuestion[] = [
  {
    id: 'an-q1',
    question: '¿Qué información puedo consultar en Analítica?',
    answer: 'Visualiza tasas de culminación de proyectos, distribución de campañas activas, snapshots de KPI y alertas de existencias.',
    tab: 'analytics',
    roles: ['admin', 'worker'],
    category: 'flujo',
    tourId: 'tour-analytics',
  },
  {
    id: 'an-q2',
    question: '¿Dónde reviso las métricas de clientes y proyectos en curso?',
    answer: 'En la sección de Tarjetas de Desempeño Consolidado encuentras el conteo actualizado de clientes y proyectos.',
    tab: 'analytics',
    roles: ['admin', 'worker'],
    category: 'gestion',
    targetElement: '[data-tour="analytics-kpis"]',
  },
  {
    id: 'an-q3',
    question: '¿Cómo superviso las alertas de inventario o stock bajo?',
    answer: 'Al final de la pantalla de Analítica dispones de la tarjeta de alertas de stock con botón de exportación.',
    tab: 'analytics',
    roles: ['admin', 'worker'],
    category: 'gestion',
    targetElement: '[data-tour="analytics-inventory-alerts"]',
  },
  {
    id: 'an-q4',
    question: '¿Cómo actualizo los datos y gráficos de analítica?',
    answer: 'Haz clic en el botón "Actualizar" del encabezado para sincronizar las métricas y reportes en tiempo real.',
    tab: 'analytics',
    roles: ['admin', 'worker'],
    category: 'gestion',
    targetElement: '[data-tour="analytics-refresh-btn"]',
    fallbackTargetElement: '[data-tour="analytics-header"]',
  },
  {
    id: 'an-q5',
    question: '¿Dónde analizo la distribución por estado de las campañas?',
    answer: 'En la tarjeta de Estado de Campañas puedes observar el gráfico de distribución y exportar los datos.',
    tab: 'analytics',
    roles: ['admin', 'worker'],
    category: 'gestion',
    targetElement: '[data-tour="analytics-campaign-chart"]',
    fallbackTargetElement: '[data-tour="analytics-kpis"]',
  },
  {
    id: 'an-q6',
    question: '¿Cómo exporto reportes ejecutivos desde analítica?',
    answer: 'Utiliza los botones de exportación CSV o Excel en Estado de Campañas, Historial de KPIs o Alertas de Inventario.',
    tab: 'analytics',
    roles: ['admin', 'worker'],
    category: 'gestion',
    targetElement: '[data-tour="analytics-inventory-alerts"]',
  },
]
