import type { CimaTourDefinition, CimaTourStep } from '../model/types'
export { collabQuestions } from './collab.questions'

const WORKSPACE_STEPS: CimaTourStep[] = [
  {
    element: '[data-tour="workspace-project-header"]',
    title: 'Informacion del Proyecto',
    description: 'Muestra el nombre del proyecto, cliente asociado, fechas limite y estado de ejecucion.',
    actionHint: 'Consulta aqui el contexto clave antes de interactuar con las actividades.',
    side: 'bottom',
    align: 'start',
    showPointer: true,
  },
  {
    element: '[data-tour="workspace-tab-board"]',
    title: 'Pestana Tablero de Tareas',
    description: 'Visualiza el flujo de trabajo operativo organizado en columnas de estado.',
    actionHint: 'Haz clic para revisar las tareas y actividades asignadas.',
    side: 'bottom',
    align: 'start',
    showPointer: true,
    switchWorkspaceTab: 'board',
  },
  {
    element: '[data-tour="workspace-task-search"]',
    title: 'Buscador de Tareas',
    description: 'Filtra actividades rapidamente por titulo, descripcion, prioridad o responsable.',
    actionHint: 'Ingresa al menos 2 caracteres para filtrar las tarjetas del tablero.',
    side: 'bottom',
    align: 'start',
    showPointer: true,
    switchWorkspaceTab: 'board',
  },
  {
    element: '[data-tour="workspace-task-columns"]',
    title: 'Columnas del Flujo de Trabajo',
    description: 'Las tarjetas progresan desde la columna inicial hasta la entrega final aprobada.',
    actionHint: 'Desliza horizontalmente para ver todas las columnas. Pulsa una tarea para ver su detalle.',
    side: 'top',
    align: 'center',
    showPointer: true,
    switchWorkspaceTab: 'board',
  },
  {
    element: '[data-tour="workspace-create-task-btn"]',
    fallbackElement: '[data-tour="workspace-task-columns"]',
    title: 'Crear Nueva Tarea',
    description: 'Permite registrar nuevas tareas tecnicas, fijar fechas limite y asignar responsables.',
    actionHint: 'Haz clic en el boton mas de la columna para agregar una actividad.',
    side: 'bottom',
    align: 'end',
    showPointer: true,
    requiredRole: ['admin', 'worker'],
    switchWorkspaceTab: 'board',
  },
  {
    element: '[data-tour="workspace-tab-chat"]',
    fallbackElement: '[data-tour="workspace-chat-channels"]',
    title: 'Pestana Conversacion y Archivos',
    description: 'Canal de mensajeria en tiempo real y repositorio de archivos del proyecto.',
    actionHint: 'Haz clic para abrir los canales de comunicacion y la documentacion.',
    side: 'bottom',
    align: 'start',
    showPointer: true,
    switchWorkspaceTab: 'chat',
  },
  {
    element: '[data-tour="workspace-chat-channels"]',
    title: 'Canales de Comunicacion',
    description: 'Alterna entre el canal interno para el equipo y el canal externo con el cliente.',
    actionHint: 'El cliente solo tiene acceso al canal externo para garantizar privacidad interna.',
    side: 'bottom',
    align: 'start',
    showPointer: true,
    switchWorkspaceTab: 'chat',
  },
  {
    element: '[data-tour="workspace-files-panel"]',
    title: 'Archivos y Repositorio Documental',
    description: 'Vincula carpetas en Google Drive o Dropbox y sube archivos con control de visibilidad.',
    actionHint: 'Administradores y trabajadores suben archivos; clientes pueden consultar y descargar.',
    side: 'left',
    align: 'start',
    showPointer: true,
    switchWorkspaceTab: 'chat',
  },
  {
    element: '[data-tour="workspace-timeline-panel"]',
    title: 'Trazabilidad y Linea de Tiempo',
    description: 'Historial cronologico de archivos compartidos, entregas completadas y cambios aprobados.',
    actionHint: 'Permite auditar cada avance y entrega del proyecto con fecha y responsable.',
    side: 'left',
    align: 'start',
    showPointer: true,
    switchWorkspaceTab: 'chat',
  },
  {
    element: '[data-tour="workspace-tab-brief"]',
    fallbackElement: '[data-tour="workspace-brief-content"]',
    title: 'Pestana Brief del Proyecto',
    description: 'Ficha tecnica con los requerimientos, especificaciones y alcance pactado.',
    actionHint: 'Haz clic para consultar las directrices y entregables acordados.',
    side: 'bottom',
    align: 'start',
    showPointer: true,
    switchWorkspaceTab: 'brief',
  },
  {
    element: '[data-tour="workspace-brief-content"]',
    title: 'Contenido del Brief',
    description: 'Revisa las especificaciones tecnicas del cliente y el historial de cambios vinculados.',
    actionHint: 'Mantiene a todo el equipo alineado con las expectativas pactadas.',
    side: 'top',
    align: 'start',
    showPointer: true,
    switchWorkspaceTab: 'brief',
  },
  {
    element: '[data-tour="workspace-tab-contract"]',
    fallbackElement: '[data-tour="workspace-contract-content"]',
    title: 'Pestana Contratos y Enmiendas',
    description: 'Documento legal formal, terminos economicos y registro de firmas electronicas.',
    actionHint: 'Clientes y administradores pueden firmar aqui de forma segura.',
    side: 'bottom',
    align: 'start',
    showPointer: true,
    requiredRole: ['admin', 'client'],
    switchWorkspaceTab: 'contract',
  },
  {
    element: '[data-tour="workspace-contract-content"]',
    title: 'Lectura y Firma Digital',
    description: 'Permite leer el contrato completo, consultar anexos (Otro si) y plasmar la firma digital.',
    actionHint: 'Cuenta con plena validez juridica y trazabilidad de firma.',
    side: 'top',
    align: 'start',
    showPointer: true,
    requiredRole: ['admin', 'client'],
    switchWorkspaceTab: 'contract',
  },
  {
    element: '[data-tour="workspace-tab-change-requests"]',
    fallbackElement: '[data-tour="workspace-change-requests-action"]',
    title: 'Pestana Solicitud de Cambios',
    description: 'Gestion formal de solicitudes de ajuste de alcance, tiempo o presupuesto (Otro si).',
    actionHint: 'Haz clic para revisar o formular solicitudes de cambio.',
    side: 'bottom',
    align: 'start',
    showPointer: true,
    switchWorkspaceTab: 'change-requests',
  },
  {
    element: '[data-tour="workspace-change-requests-action"]',
    title: 'Formulacion y Aprobacion de Cambios',
    description: 'Los clientes solicitan ajustes puntuales. Los administradores revisan y autorizan o rechazan.',
    actionHint: 'Evita desvios no autorizados en el alcance del proyecto.',
    side: 'bottom',
    align: 'start',
    showPointer: true,
    switchWorkspaceTab: 'change-requests',
  },
  {
    element: '[data-tour="workspace-tab-members"]',
    fallbackElement: '[data-tour="workspace-members-list"]',
    title: 'Pestana Integrantes del Proyecto',
    description: 'Lista del equipo de trabajo y representantes del cliente asignados al proyecto.',
    actionHint: 'Haz clic para ver el personal asignado y sus roles.',
    side: 'bottom',
    align: 'start',
    showPointer: true,
    switchWorkspaceTab: 'members',
  },
  {
    element: '[data-tour="workspace-members-list"]',
    title: 'Equipo Asignado',
    description: 'Consulta los miembros del equipo, sus especialidades y su ultima actividad.',
    actionHint: 'Muestra a todos los involucrados en el cumplimiento de los objetivos.',
    side: 'top',
    align: 'start',
    showPointer: true,
    switchWorkspaceTab: 'members',
  },
  {
    element: '[data-tour="workspace-members-invite"]',
    title: 'Asignar Colaboradores al Proyecto',
    description: 'Los administradores pueden buscar profesionales por nombre o correo e incorporarlos al equipo.',
    actionHint: 'Selecciona al colaborador y presiona Agregar al equipo.',
    side: 'bottom',
    align: 'start',
    showPointer: true,
    requiredRole: ['admin'],
    switchWorkspaceTab: 'members',
  },
  {
    element: '[data-tour="workspace-back-btn"]',
    title: 'Volver a Proyectos',
    description: 'Regresa a la vista general del tablero Kanban de proyectos en cualquier momento.',
    actionHint: 'Haz clic para salir del espacio de trabajo del proyecto.',
    side: 'bottom',
    align: 'start',
    showPointer: true,
  },
]

export const collabKanbanTour: CimaTourDefinition = {
  id: 'tour-collab-kanban',
  tab: 'collab',
  title: 'Recorrido del Tablero y Proyectos',
  description: 'Conoce como explorar el tablero kanban e interactuar con cada espacio de trabajo.',
  roles: ['admin', 'worker', 'client'],
  steps: [
    {
      element: '[data-tour="collab-search"]',
      title: 'Buscador de Proyectos',
      description: 'Escribe el nombre del proyecto, cliente o correo para localizarlo al instante.',
      actionHint: 'Escribe al menos 2 letras para iniciar la busqueda en tiempo real.',
      side: 'bottom',
      align: 'start',
      showPointer: true,
    },
    {
      element: '[data-tour="collab-summary"]',
      title: 'Resumen Rapido de Estados',
      description: 'Muestra el conteo de proyectos en cada etapa y el estado general de avance.',
      actionHint: 'Permite evaluar la carga de trabajo global en un solo vistazo.',
      side: 'bottom',
      align: 'center',
      showPointer: true,
    },
    {
      element: '[data-tour="collab-columns-container"]',
      fallbackElement: '[data-tour="collab-column-TODO"]',
      title: 'Columnas de Progreso Kanban',
      description: 'Los proyectos avanzan de izquierda a derecha: Por Iniciar, En Proceso, En Revision y Completado.',
      actionHint: 'Desliza horizontalmente en movil para explorar todas las columnas y sus proyectos.',
      side: 'top',
      align: 'center',
      showPointer: true,
    },
    {
      element: '[data-tour="collab-create-btn"]',
      title: 'Crear un Nuevo Proyecto',
      description: 'Permite registrar un nuevo proyecto asignando cliente, fechas y alcance acordado.',
      actionHint: 'Haz clic aqui para abrir el formulario de creacion.',
      side: 'bottom',
      align: 'end',
      showPointer: true,
      requiredRole: ['admin'],
    },
    {
      element: '[data-tour="collab-card-first"]',
      fallbackElement: '[data-tour="collab-columns-container"]',
      title: 'Abrir Espacio de Trabajo',
      description: 'Ingresa al espacio de trabajo completo para gestionar tareas, chat, brief y contratos.',
      actionHint: 'Haz clic en la tarjeta o en Siguiente para abrir este proyecto.',
      side: 'right',
      align: 'start',
      showPointer: true,
      onNextAction: 'openProject',
    },
    ...WORKSPACE_STEPS,
  ],
}

export const collabWorkspaceTour: CimaTourDefinition = {
  id: 'tour-collab-workspace',
  tab: 'collab',
  title: 'Espacio de Trabajo del Proyecto',
  description: 'Guia interactiva para navegar por tareas, chat, brief, archivos, cambios y contratos.',
  roles: ['admin', 'worker', 'client'],
  steps: WORKSPACE_STEPS,
}
