import type { CimaTourDefinition, GuidedQuestion } from '../model/types'

export const collabKanbanTour: CimaTourDefinition = {
  id: 'tour-collab-kanban',
  tab: 'collab',
  title: 'Recorrido del Tablero de Proyectos',
  description: 'Conoce como explorar, filtrar y acceder a tus proyectos de trabajo en el CRM.',
  roles: ['admin', 'worker', 'client'],
  steps: [
    {
      element: '[data-tour="collab-search"]',
      title: 'Buscador de Proyectos',
      description: 'Escribe el nombre del proyecto, cliente o correo para localizarlo al instante.',
      actionHint: 'Escribe al menos 2 letras para iniciar la busqueda en tiempo real.',
      side: 'bottom',
      align: 'start',
      showPointer: true,
    },
    {
      element: '[data-tour="collab-summary"]',
      title: 'Resumen Rapido de Estados',
      description: 'Muestra el conteo de proyectos en cada etapa y el estado general de avance.',
      actionHint: 'Permite evaluar la carga de trabajo global en un solo vistazo.',
      side: 'bottom',
      align: 'center',
      showPointer: true,
    },
    {
      element: '[data-tour="collab-columns-container"]',
      title: 'Columnas de Progreso Kanban',
      description: 'Los proyectos avanzan de izquierda a derecha: Por Iniciar, En Proceso, En Revision y Completado.',
      actionHint: 'Cada columna reune los proyectos segun su etapa actual.',
      side: 'top',
      align: 'center',
      showPointer: true,
    },
    {
      element: '[data-tour="collab-create-btn"]',
      title: 'Crear un Nuevo Proyecto',
      description: 'Permite registrar un nuevo proyecto asignando cliente, fechas y alcance acordado.',
      actionHint: 'Haz clic aqui para abrir el formulario de creacion.',
      side: 'bottom',
      align: 'end',
      showPointer: true,
      requiredRole: ['admin'],
    },
    {
      element: '[data-tour="collab-card-first"]',
      title: 'Abrir Espacio de Trabajo',
      description: 'Haz clic sobre cualquier tarjeta para ingresar al espacio de trabajo completo del proyecto.',
      actionHint: 'Accede a las tareas, la conversacion, el brief, los contratos y los archivos.',
      side: 'right',
      align: 'start',
      showPointer: true,
    },
  ],
}

export const collabWorkspaceTour: CimaTourDefinition = {
  id: 'tour-collab-workspace',
  tab: 'collab',
  title: 'Espacio de Trabajo del Proyecto',
  description: 'Guia interactiva para navegar por tareas, chat, brief, archivos, cambios y contratos.',
  roles: ['admin', 'worker', 'client'],
  steps: [
    {
      element: '[data-tour="workspace-back-btn"]',
      title: 'Volver a Proyectos',
      description: 'Regresa a la vista general del tablero Kanban de proyectos en cualquier momento.',
      actionHint: 'Haz clic para salir del espacio de trabajo del proyecto.',
      side: 'bottom',
      align: 'start',
      showPointer: true,
    },
    {
      element: '[data-tour="workspace-project-header"]',
      title: 'Informacion del Proyecto',
      description: 'Muestra el nombre del proyecto, cliente asociado, fechas limite y estado de ejecucion.',
      actionHint: 'Consulta aqui el contexto clave antes de interactuar con las actividades.',
      side: 'bottom',
      align: 'start',
      showPointer: true,
    },
    {
      element: '[data-tour="workspace-tab-board"]',
      title: 'Pestana Tablero de Tareas',
      description: 'Visualiza el flujo de trabajo operativo organizado en columnas de estado.',
      actionHint: 'Haz clic para revisar las tareas y actividades asignadas.',
      side: 'bottom',
      align: 'start',
      showPointer: true,
      switchWorkspaceTab: 'board',
    },
    {
      element: '[data-tour="workspace-task-search"]',
      title: 'Buscador de Tareas',
      description: 'Filtra actividades rapidamente por titulo, descripcion, prioridad o responsable.',
      actionHint: 'Ingresa al menos 2 caracteres para filtrar las tarjetas del tablero.',
      side: 'bottom',
      align: 'start',
      showPointer: true,
      switchWorkspaceTab: 'board',
    },
    {
      element: '[data-tour="workspace-task-columns"]',
      title: 'Columnas del Flujo de Trabajo',
      description: 'Las tarjetas progresan desde la columna inicial hasta la entrega final aprobada.',
      actionHint: 'Pulsa sobre cualquier tarea para ver subtareas, checklist y comentarios.',
      side: 'top',
      align: 'center',
      showPointer: true,
      switchWorkspaceTab: 'board',
    },
    {
      element: '[data-tour="workspace-create-task-btn"]',
      title: 'Crear Nueva Tarea',
      description: 'Permite registrar nuevas tareas tecnicas, fijar fechas limite y asignar responsables.',
      actionHint: 'Haz clic en el boton mas de la columna para agregar una actividad.',
      side: 'bottom',
      align: 'end',
      showPointer: true,
      requiredRole: ['admin', 'worker'],
      switchWorkspaceTab: 'board',
    },
    {
      element: '[data-tour="workspace-tab-chat"]',
      title: 'Pestana Conversacion y Archivos',
      description: 'Canal de mensajeria en tiempo real y repositorio de archivos del proyecto.',
      actionHint: 'Haz clic para abrir los canales de comunicacion y la documentacion.',
      side: 'bottom',
      align: 'start',
      showPointer: true,
      switchWorkspaceTab: 'chat',
    },
    {
      element: '[data-tour="workspace-chat-channels"]',
      title: 'Canales de Comunicacion',
      description: 'Alterna entre el canal interno para el equipo y el canal externo con el cliente.',
      actionHint: 'El cliente solo tiene acceso al canal externo para garantizar privacidad interna.',
      side: 'bottom',
      align: 'start',
      showPointer: true,
      switchWorkspaceTab: 'chat',
    },
    {
      element: '[data-tour="workspace-files-panel"]',
      title: 'Archivos y Repositorio Documental',
      description: 'Vincula carpetas en Google Drive o Dropbox y sube archivos con control de visibilidad.',
      actionHint: 'Administradores y trabajadores suben archivos; clientes pueden consultar y descargar.',
      side: 'left',
      align: 'start',
      showPointer: true,
      switchWorkspaceTab: 'chat',
    },
    {
      element: '[data-tour="workspace-timeline-panel"]',
      title: 'Trazabilidad y Linea de Tiempo',
      description: 'Historial cronologico de archivos compartidos, entregas completadas y cambios aprobados.',
      actionHint: 'Permite auditar cada avance y entrega del proyecto con fecha y responsable.',
      side: 'left',
      align: 'start',
      showPointer: true,
      switchWorkspaceTab: 'chat',
    },
    {
      element: '[data-tour="workspace-tab-brief"]',
      title: 'Pestana Brief del Proyecto',
      description: 'Ficha tecnica con los requerimientos, especificaciones y alcance pactado.',
      actionHint: 'Haz clic para consultar las directrices y entregables acordados.',
      side: 'bottom',
      align: 'start',
      showPointer: true,
      switchWorkspaceTab: 'brief',
    },
    {
      element: '[data-tour="workspace-brief-content"]',
      title: 'Contenido del Brief',
      description: 'Revisa las especificaciones tecnicas del cliente y el historial de cambios vinculados.',
      actionHint: 'Mantiene a todo el equipo alineado con las expectativas pactadas.',
      side: 'top',
      align: 'start',
      showPointer: true,
      switchWorkspaceTab: 'brief',
    },
    {
      element: '[data-tour="workspace-tab-contract"]',
      title: 'Pestana Contratos y Enmiendas',
      description: 'Documento legal formal, terminos economicos y registro de firmas electronicas.',
      actionHint: 'Clientes y administradores pueden firmar aqui de forma segura.',
      side: 'bottom',
      align: 'start',
      showPointer: true,
      switchWorkspaceTab: 'contract',
    },
    {
      element: '[data-tour="workspace-contract-content"]',
      title: 'Lectura y Firma Digital',
      description: 'Permite leer el contrato completo, consultar anexos (Otro si) y plasmar la firma digital.',
      actionHint: 'Cuenta con plena validez juridica y trazabilidad de firma.',
      side: 'top',
      align: 'start',
      showPointer: true,
      switchWorkspaceTab: 'contract',
    },
    {
      element: '[data-tour="workspace-tab-change-requests"]',
      title: 'Pestana Solicitud de Cambios',
      description: 'Gestion formal de solicitudes de ajuste de alcance, tiempo o presupuesto (Otro si).',
      actionHint: 'Haz clic para revisar o formular solicitudes de cambio.',
      side: 'bottom',
      align: 'start',
      showPointer: true,
      switchWorkspaceTab: 'change-requests',
    },
    {
      element: '[data-tour="workspace-change-requests-action"]',
      title: 'Formulacion y Aprobacion de Cambios',
      description: 'Los clientes solicitan ajustes puntuales. Los administradores revisan y autorizan o rechazan.',
      actionHint: 'Evita desvios no autorizados en el alcance del proyecto.',
      side: 'bottom',
      align: 'start',
      showPointer: true,
      switchWorkspaceTab: 'change-requests',
    },
    {
      element: '[data-tour="workspace-tab-members"]',
      title: 'Pestana Integrantes del Proyecto',
      description: 'Lista del equipo de trabajo y representantes del cliente asignados al proyecto.',
      actionHint: 'Haz clic para ver el personal asignado y sus roles.',
      side: 'bottom',
      align: 'start',
      showPointer: true,
      switchWorkspaceTab: 'members',
    },
    {
      element: '[data-tour="workspace-members-list"]',
      title: 'Equipo Asignado',
      description: 'Consulta los miembros del equipo, sus especialidades y su ultima actividad.',
      actionHint: 'Muestra a todos los involucrados en el cumplimiento de los objetivos.',
      side: 'top',
      align: 'start',
      showPointer: true,
      switchWorkspaceTab: 'members',
    },
    {
      element: '[data-tour="workspace-members-invite"]',
      title: 'Asignar Colaboradores al Proyecto',
      description: 'Los administradores pueden buscar profesionales por nombre o correo e incorporarlos al equipo.',
      actionHint: 'Selecciona al colaborador y presiona Agregar al equipo.',
      side: 'bottom',
      align: 'start',
      showPointer: true,
      requiredRole: ['admin'],
      switchWorkspaceTab: 'members',
    },
  ],
}

export const collabQuestions: GuidedQuestion[] = [
  {
    id: 'collab-q1',
    question: 'Como encuentro un proyecto en el tablero?',
    answer: 'Usa la barra de busqueda en la parte superior. Al escribir 2 caracteres se filtran las tarjetas.',
    tab: 'collab',
    scope: 'kanban',
    roles: ['admin', 'worker', 'client'],
    category: 'gestion',
    targetElement: '[data-tour="collab-search"]',
  },
  {
    id: 'collab-q2',
    question: 'Como ingreso a ver las tareas y detalles de un proyecto?',
    answer: 'Haz clic sobre la tarjeta del proyecto en el tablero kanban para abrir su espacio de trabajo.',
    tab: 'collab',
    scope: 'kanban',
    roles: ['admin', 'worker', 'client'],
    category: 'flujo',
    targetElement: '[data-tour="collab-card-first"]',
  },
  {
    id: 'collab-q3',
    question: 'Como creo un nuevo proyecto?',
    answer: 'Si tienes rol Administrador, pulsa el boton Nuevo proyecto ubicado arriba a la derecha.',
    tab: 'collab',
    scope: 'kanban',
    roles: ['admin'],
    category: 'gestion',
    targetElement: '[data-tour="collab-create-btn"]',
  },
  {
    id: 'collab-q4',
    question: 'Como me comunico en el chat interno y con el cliente?',
    answer: 'En la pestana Conversacion, elige el canal interno para el equipo o externo para dialogar con el cliente.',
    tab: 'collab',
    scope: 'workspace',
    workspaceTab: 'chat',
    roles: ['admin', 'worker', 'client'],
    category: 'comunicacion',
    targetElement: '[data-tour="workspace-chat-channels"]',
  },
  {
    id: 'collab-q5',
    question: 'Donde subo y descargo archivos o enlazo carpetas externas?',
    answer: 'En la pestana Conversacion, usa el panel lateral Archivos para subir documentos o vincular Google Drive.',
    tab: 'collab',
    scope: 'workspace',
    workspaceTab: 'chat',
    roles: ['admin', 'worker', 'client'],
    category: 'gestion',
    targetElement: '[data-tour="workspace-files-panel"]',
  },
  {
    id: 'collab-q6',
    question: 'Donde consulto el Brief con los requerimientos del proyecto?',
    answer: 'En la pestana Brief encontraras la ficha tecnica, los objetivos acordados y el historial de cambios.',
    tab: 'collab',
    scope: 'workspace',
    workspaceTab: 'brief',
    roles: ['admin', 'worker', 'client'],
    category: 'gestion',
    targetElement: '[data-tour="workspace-brief-content"]',
  },
  {
    id: 'collab-q7',
    question: 'Donde reviso y firmo el contrato del proyecto?',
    answer: 'En la pestana Contrato puedes leer los terminos contractuales y realizar la firma electronica segura.',
    tab: 'collab',
    scope: 'workspace',
    workspaceTab: 'contract',
    roles: ['admin', 'client'],
    category: 'gestion',
    targetElement: '[data-tour="workspace-contract-content"]',
  },
  {
    id: 'collab-q8',
    question: 'Como solicito un cambio o ajuste de alcance (Otro si)?',
    answer: 'En la pestana Solicitud de cambios, pulsa Solicitar cambio para formalizar un ajuste en alcance o tiempo.',
    tab: 'collab',
    scope: 'workspace',
    workspaceTab: 'change-requests',
    roles: ['client'],
    category: 'flujo',
    targetElement: '[data-tour="workspace-change-requests-action"]',
  },
  {
    id: 'collab-q9',
    question: 'Como evalua el administrador las solicitudes de cambio?',
    answer: 'En Solicitud de cambios, el administrador puede revisar el requerimiento y Aceptar o Rechazar formalmente.',
    tab: 'collab',
    scope: 'workspace',
    workspaceTab: 'change-requests',
    roles: ['admin'],
    category: 'gestion',
    targetElement: '[data-tour="workspace-change-requests-action"]',
  },
  {
    id: 'collab-q10',
    question: 'Quienes integran el proyecto y como agrego mas colaboradores?',
    answer: 'En la pestana Integrantes ves al equipo asignado. Los administradores disponen del buscador para agregar mas miembros.',
    tab: 'collab',
    scope: 'workspace',
    workspaceTab: 'members',
    roles: ['admin', 'worker', 'client'],
    category: 'gestion',
    targetElement: '[data-tour="workspace-members-list"]',
  },
  {
    id: 'collab-q11',
    question: 'Como creo una nueva tarea en el tablero operativo?',
    answer: 'En la pestana Tablero, los administradores y trabajadores pueden pulsar el boton mas en la columna para crear tareas.',
    tab: 'collab',
    scope: 'workspace',
    workspaceTab: 'board',
    roles: ['admin', 'worker'],
    category: 'flujo',
    targetElement: '[data-tour="workspace-create-task-btn"]',
  },
]
