import type { GuidedQuestion } from '../model/types'

export const collabQuestions: GuidedQuestion[] = [
  {
    id: 'collab-q1',
    question: 'Como encuentro un proyecto en el tablero?',
    answer: 'Usa la barra de busqueda en la parte superior. Al escribir 2 caracteres se filtran las tarjetas en tiempo real.',
    tab: 'collab',
    scope: 'kanban',
    roles: ['admin', 'worker', 'client'],
    category: 'gestion',
    targetElement: '[data-tour="collab-search"]',
  },
  {
    id: 'collab-q2',
    question: 'Como consulto el estado y avance global de proyectos?',
    answer: 'El bloque superior de metricas resume el total de proyectos organizados por etapa de ejecucion.',
    tab: 'collab',
    scope: 'kanban',
    roles: ['admin', 'worker', 'client'],
    category: 'gestion',
    targetElement: '[data-tour="collab-summary"]',
  },
  {
    id: 'collab-q3',
    question: 'Como creo un nuevo proyecto?',
    answer: 'Si tienes rol Administrador, pulsa el boton Nuevo proyecto ubicado arriba a la derecha.',
    tab: 'collab',
    scope: 'kanban',
    roles: ['admin'],
    category: 'gestion',
    targetElement: '[data-tour="collab-create-btn"]',
  },
  {
    id: 'collab-q4',
    question: 'Como ingreso al espacio de trabajo completo de un proyecto?',
    answer: 'Haz clic sobre cualquier tarjeta en el tablero kanban para acceder a sus tareas, chat, brief y contratos.',
    tab: 'collab',
    scope: 'all',
    roles: ['admin', 'worker', 'client'],
    category: 'flujo',
    targetElement: '[data-tour="collab-card-first"]',
  },
  {
    id: 'collab-q5',
    question: 'Donde veo las tareas y actividades asignadas en el proyecto?',
    answer: 'En la pestana Tablero encuentras las columnas operativas con cada tarea, sus subtareas y responsables.',
    tab: 'collab',
    scope: 'workspace',
    workspaceTab: 'board',
    roles: ['admin', 'worker', 'client'],
    category: 'flujo',
    targetElement: '[data-tour="workspace-tab-board"]',
  },
  {
    id: 'collab-q6',
    question: 'Como busco o filtro tareas dentro del espacio de trabajo?',
    answer: 'Utiliza el buscador integrado en el tablero operativo para filtrar actividades por titulo o prioridad.',
    tab: 'collab',
    scope: 'workspace',
    workspaceTab: 'board',
    roles: ['admin', 'worker', 'client'],
    category: 'gestion',
    targetElement: '[data-tour="workspace-task-search"]',
  },
  {
    id: 'collab-q7',
    question: 'Como creo una nueva tarea en el tablero operativo?',
    answer: 'Los administradores y colaboradores pueden pulsar el boton mas en la cabecera de la columna correspondiente.',
    tab: 'collab',
    scope: 'workspace',
    workspaceTab: 'board',
    roles: ['admin', 'worker'],
    category: 'flujo',
    targetElement: '[data-tour="workspace-create-task-btn"]',
  },
  {
    id: 'collab-q8',
    question: 'Como me comunico en el chat interno y con el cliente?',
    answer: 'En la pestana Conversacion, elige el canal interno para el equipo o externo para dialogar con el cliente.',
    tab: 'collab',
    scope: 'workspace',
    workspaceTab: 'chat',
    roles: ['admin', 'worker', 'client'],
    category: 'comunicacion',
    targetElement: '[data-tour="workspace-chat-channels"]',
  },
  {
    id: 'collab-q9',
    question: 'Donde subo y descargo archivos o enlazo carpetas externas?',
    answer: 'En la pestana Conversacion, usa el panel lateral Archivos para cargar documentos o vincular almacenamiento en la nube.',
    tab: 'collab',
    scope: 'workspace',
    workspaceTab: 'chat',
    roles: ['admin', 'worker', 'client'],
    category: 'gestion',
    targetElement: '[data-tour="workspace-files-panel"]',
  },
  {
    id: 'collab-q10',
    question: 'Donde reviso la linea de tiempo y entregables del proyecto?',
    answer: 'En la pestana Conversacion, el panel Linea de tiempo registra cronologicamente cada hito y archivo compartido.',
    tab: 'collab',
    scope: 'workspace',
    workspaceTab: 'chat',
    roles: ['admin', 'worker', 'client'],
    category: 'gestion',
    targetElement: '[data-tour="workspace-timeline-panel"]',
  },
  {
    id: 'collab-q11',
    question: 'Donde consulto el Brief con los requerimientos del proyecto?',
    answer: 'En la pestana Brief encontraras la ficha tecnica, los objetivos pactados y el historial de versiones del alcance.',
    tab: 'collab',
    scope: 'workspace',
    workspaceTab: 'brief',
    roles: ['admin', 'worker', 'client'],
    category: 'gestion',
    targetElement: '[data-tour="workspace-brief-content"]',
  },
  {
    id: 'collab-q12',
    question: 'Donde reviso y firmo el contrato del proyecto?',
    answer: 'En la pestana Contrato puedes examinar las clausulas legales, anexos y realizar la firma electronica segura.',
    tab: 'collab',
    scope: 'workspace',
    workspaceTab: 'contract',
    roles: ['admin', 'client'],
    category: 'gestion',
    targetElement: '[data-tour="workspace-contract-content"]',
  },
  {
    id: 'collab-q13',
    question: 'Como solicito un cambio o ajuste de alcance como cliente?',
    answer: 'En la pestana Solicitud de cambios, pulsa Solicitar cambio para detallar los requerimientos de la enmienda.',
    tab: 'collab',
    scope: 'workspace',
    workspaceTab: 'change-requests',
    roles: ['client'],
    category: 'flujo',
    targetElement: '[data-tour="workspace-change-requests-action"]',
  },
  {
    id: 'collab-q14',
    question: 'Como evalua el administrador las solicitudes de cambio?',
    answer: 'En Solicitud de cambios, el administrador revisa el impacto en alcance y autoriza o rechaza formalmente la solicitud.',
    tab: 'collab',
    scope: 'workspace',
    workspaceTab: 'change-requests',
    roles: ['admin'],
    category: 'gestion',
    targetElement: '[data-tour="workspace-change-requests-action"]',
  },
  {
    id: 'collab-q15',
    question: 'Quienes integran el proyecto y como agrego mas colaboradores?',
    answer: 'En la pestana Integrantes ves al equipo asignado. Los administradores disponen del buscador para sumar miembros.',
    tab: 'collab',
    scope: 'workspace',
    workspaceTab: 'members',
    roles: ['admin', 'worker', 'client'],
    category: 'gestion',
    targetElement: '[data-tour="workspace-members-list"]',
  },
  {
    id: 'collab-q16',
    question: 'Como regresa el usuario al tablero kanban principal?',
    answer: 'Usa el boton Proyectos en la barra superior del espacio de trabajo para volver al tablero general.',
    tab: 'collab',
    scope: 'all',
    roles: ['admin', 'worker', 'client'],
    category: 'flujo',
    targetElement: '[data-tour="workspace-back-btn"]',
  },
]
