import type { CimaTourDefinition, GuidedQuestion } from '../model/types'

export const collabKanbanTour: CimaTourDefinition = {
  id: 'tour-collab-kanban',
  tab: 'collab',
  title: 'Recorrido del Tablero de Proyectos',
  description: 'Conoce cómo explorar, filtrar y acceder a tus proyectos de trabajo en el CRM.',
  roles: ['admin', 'worker', 'client'],
  steps: [
    {
      element: '[data-tour="collab-search"]',
      title: 'Buscador de Proyectos',
      description: 'Escribe el nombre del proyecto o cliente para encontrarlo inmediatamente.',
      actionHint: 'Escribe al menos 2 letras para iniciar la búsqueda.',
      side: 'bottom',
      align: 'start',
      showPointer: true,
    },
    {
      element: '[data-tour="collab-summary"]',
      title: 'Resumen Rápido de Estados',
      description: 'Muestra cuántos proyectos hay en cada estado y el porcentaje promedio de avance.',
      actionHint: 'Útil para tener una perspectiva global inmediata.',
      side: 'bottom',
      align: 'center',
      showPointer: true,
    },
    {
      element: '[data-tour="collab-columns-container"]',
      title: 'Columnas de Progreso',
      description: 'Los proyectos avanzan de izquierda a derecha: Por Iniciar, En Proceso, En Revisión y Completado.',
      actionHint: 'Cada columna agrupa los proyectos según su etapa actual.',
      side: 'top',
      align: 'center',
      showPointer: true,
    },
    {
      element: '[data-tour="collab-create-btn"]',
      title: 'Crear un Nuevo Proyecto',
      description: 'Permite registrar un nuevo proyecto asignando cliente, fechas y alcance.',
      actionHint: 'Haz clic aquí para abrir el formulario de creación.',
      side: 'bottom',
      align: 'end',
      showPointer: true,
      requiredRole: ['admin'],
    },
    {
      element: '[data-tour="collab-card-first"]',
      title: 'Abrir un Proyecto',
      description: 'Haz clic sobre cualquier tarjeta para ingresar a su espacio de trabajo completo.',
      actionHint: 'Al hacer clic, entrarás al tablero de tareas, chat y contratos del proyecto.',
      side: 'right',
      align: 'start',
      showPointer: true,
    },
  ],
}

export const collabWorkspaceTour: CimaTourDefinition = {
  id: 'tour-collab-workspace',
  tab: 'collab',
  title: 'Recorrido del Espacio de Trabajo del Proyecto',
  description: 'Aprende a navegar por las tareas, la conversación, los contratos y las solicitudes de cambio.',
  roles: ['admin', 'worker', 'client'],
  steps: [
    {
      element: '[data-tour="workspace-back-btn"]',
      title: 'Volver al Tablero de Proyectos',
      description: 'Pulsa este botón en cualquier momento para regresar a la vista general de proyectos.',
      actionHint: 'Haz clic aquí para volver atrás.',
      side: 'bottom',
      align: 'start',
      showPointer: true,
    },
    {
      element: '[data-tour="workspace-tabs"]',
      title: 'Pestañas del Proyecto',
      description: 'Navega entre el Tablero de tareas, la Conversación (Chat), el Brief, el Contrato y las Solicitudes de Cambio.',
      actionHint: 'Haz clic en cada pestaña para cambiar de sección.',
      side: 'bottom',
      align: 'center',
      showPointer: true,
    },
    {
      element: '[data-tour="workspace-tab-board"]',
      title: 'Tablero de Tareas',
      description: 'Aquí se visualizan las actividades del proyecto divididas por columnas de estado.',
      actionHint: 'Puedes pulsar sobre una tarjeta de tarea para ver sus detalles o subir entregables.',
      side: 'bottom',
      align: 'start',
      showPointer: true,
    },
    {
      element: '[data-tour="workspace-tab-chat"]',
      title: 'Canal de Conversación',
      description: 'Espacio de chat directo. Permite canal interno (solo equipo) y externo (con el cliente).',
      actionHint: 'Utiliza el chat para resolver dudas, enviar menciones y compartir archivos.',
      side: 'bottom',
      align: 'start',
      showPointer: true,
    },
    {
      element: '[data-tour="workspace-tab-contract"]',
      title: 'Contratos y Firmas Digitales',
      description: 'Consulta los términos contractuales, montos y procede a la firma electrónica segura.',
      actionHint: 'Clientes y administradores pueden gestionar y firmar aquí sus documentos legales.',
      side: 'bottom',
      align: 'start',
      showPointer: true,
    },
  ],
}

export const collabQuestions: GuidedQuestion[] = [
  {
    id: 'collab-q1',
    question: '¿Cómo encuentro un proyecto en el tablero?',
    answer: 'Usa la barra de búsqueda en la parte superior del tablero. Con solo escribir 2 caracteres se filtrarán las tarjetas.',
    tab: 'collab',
    roles: ['admin', 'worker', 'client'],
    category: 'gestion',
    targetElement: '[data-tour="collab-search"]',
  },
  {
    id: 'collab-q2',
    question: '¿Cómo ingreso a ver las tareas y detalles de un proyecto?',
    answer: 'Haz clic directamente sobre la tarjeta del proyecto en el tablero de columnas para abrir su espacio de trabajo.',
    tab: 'collab',
    roles: ['admin', 'worker', 'client'],
    category: 'flujo',
    targetElement: '[data-tour="collab-card-first"]',
  },
  {
    id: 'collab-q3',
    question: '¿Cómo creo un nuevo proyecto?',
    answer: 'Si tienes rol Administrador, pulsa el botón rojo "+ Nuevo Proyecto" ubicado arriba a la derecha.',
    tab: 'collab',
    roles: ['admin'],
    category: 'gestion',
    targetElement: '[data-tour="collab-create-btn"]',
  },
  {
    id: 'collab-q4',
    question: '¿Cómo me comunico con el cliente o con el equipo?',
    answer: 'Dentro del proyecto, ve a la pestaña "Conversación". Selecciona el canal externo para comunicarte con el cliente o interno para notas del equipo.',
    tab: 'collab',
    roles: ['admin', 'worker', 'client'],
    category: 'comunicacion',
    targetElement: '[data-tour="workspace-tab-chat"]',
  },
  {
    id: 'collab-q5',
    question: '¿Dónde reviso y firmo el contrato del proyecto?',
    answer: 'Dentro del espacio del proyecto, haz clic en la pestaña "Contrato". Allí podrás leer el documento y realizar la firma digital.',
    tab: 'collab',
    roles: ['admin', 'client'],
    category: 'gestion',
    targetElement: '[data-tour="workspace-tab-contract"]',
  },
  {
    id: 'collab-q6',
    question: '¿Cómo solicito un cambio o ajuste en el alcance (Otro sí)?',
    answer: 'En el espacio del proyecto, pulsa la pestaña "Solicitud de cambios" para radicar o autorizar modificaciones formales.',
    tab: 'collab',
    roles: ['admin', 'worker', 'client'],
    category: 'gestion',
    targetElement: '[data-tour="workspace-tab-change-requests"]',
  },
]
