import type { CimaTourStep } from '../model/types'

export const KANBAN_STEPS: CimaTourStep[] = [
  {
    element: '[data-tour="collab-search"]',
    title: 'Buscador de Proyectos',
    description: 'Escribe el nombre del proyecto, cliente o correo para localizarlo al instante.',
    actionHint: 'Escribe al menos 2 letras para iniciar la busqueda en tiempo real.',
    side: 'bottom',
    align: 'start',
    showPointer: true,
    interactiveAction: 'input',
  },
  {
    element: '[data-tour="collab-summary"]',
    title: 'Resumen Rapido de Estados',
    description: 'Muestra el conteo de proyectos en cada etapa y el estado general de avance.',
    actionHint: 'Permite evaluar la carga de trabajo global en un solo vistazo.',
    side: 'bottom',
    align: 'center',
    showPointer: true,
  },
  {
    element: '[data-tour="collab-columns-container"]',
    fallbackElement: '[data-tour="collab-column-TODO"]',
    title: 'Columnas de Progreso Kanban',
    description: 'Los proyectos avanzan de izquierda a derecha: Por Iniciar, En Proceso, En Revision y Completado.',
    actionHint: 'Desliza horizontalmente en movil para explorar todas las columnas y sus proyectos.',
    side: 'top',
    align: 'center',
    showPointer: true,
  },
  {
    element: '[data-tour="collab-create-btn"]',
    title: 'Crear un Nuevo Proyecto',
    description: 'Permite registrar un nuevo proyecto asignando cliente, fechas y alcance acordado.',
    actionHint: 'Haz clic aqui para abrir el formulario de creacion.',
    side: 'bottom',
    align: 'end',
    showPointer: true,
    targetPulse: true,
    requiredRole: ['admin'],
    interactiveAction: 'open-modal',
  },
  {
    element: '[data-tour="collab-card-first"]',
    fallbackElement: '[data-tour="collab-columns-container"]',
    title: 'Abrir Espacio de Trabajo',
    description: 'Ingresa al espacio de trabajo completo para gestionar tareas, chat, brief y contratos.',
    emptyStateDescription:
      'Aun no tienes proyectos registrados. Explora las columnas o pulsa "Crear Proyecto" para iniciar tu primera entrega.',
    actionHint: 'Haz clic en la tarjeta o en Siguiente para abrir este proyecto.',
    side: 'right',
    align: 'start',
    showPointer: true,
    targetPulse: true,
    onNextAction: 'openProject',
    interactiveAction: 'click',
  },
]

export const TASK_STEPS: CimaTourStep[] = [
  {
    element: '[data-tour="workspace-project-header"]',
    title: 'Informacion del Proyecto',
    description: 'Muestra el nombre del proyecto, cliente asociado, fechas limite y estado de ejecucion.',
    actionHint: 'Consulta aqui el contexto clave antes de interactuar con las actividades.',
    side: 'bottom',
    align: 'start',
    showPointer: true,
  },
  {
    element: '[data-tour="workspace-tab-board"]',
    title: 'Pestana Tablero de Tareas',
    description: 'Visualiza el flujo de trabajo operativo organizado en columnas de estado.',
    actionHint: 'Haz clic para revisar las tareas y actividades asignadas.',
    side: 'bottom',
    align: 'start',
    showPointer: true,
    switchWorkspaceTab: 'board',
    interactiveAction: 'tab-change',
  },
  {
    element: '[data-tour="workspace-task-columns"]',
    title: 'Columnas del Flujo de Trabajo',
    description: 'Las tarjetas progresan desde la columna inicial hasta la entrega final aprobada.',
    actionHint: 'Desliza horizontalmente para ver todas las columnas. Pulsa una tarea para ver su detalle.',
    side: 'top',
    align: 'center',
    showPointer: true,
    switchWorkspaceTab: 'board',
  },
  {
    element: '[data-tour="workspace-create-task-btn"]',
    fallbackElement: '[data-tour="workspace-task-columns"]',
    title: 'Crear Nueva Tarea',
    description: 'Permite registrar nuevas tareas tecnicas, fijar fechas limite y asignar responsables.',
    emptyStateDescription:
      'Explora las columnas del flujo operativo o pulsa el boton mas para registrar tu primera actividad.',
    actionHint: 'Haz clic en el boton mas de la columna para agregar una actividad.',
    side: 'bottom',
    align: 'end',
    showPointer: true,
    targetPulse: true,
    requiredRole: ['admin', 'worker'],
    switchWorkspaceTab: 'board',
    interactiveAction: 'open-modal',
  },
]

export const DOC_STEPS: CimaTourStep[] = [
  {
    element: '[data-tour="workspace-tab-chat"]',
    fallbackElement: '[data-tour="workspace-chat-channels"]',
    title: 'Pestana Conversacion y Archivos',
    description: 'Canal de mensajeria en tiempo real y repositorio de archivos del proyecto.',
    actionHint: 'Haz clic para abrir los canales de comunicacion y la documentacion.',
    side: 'bottom',
    align: 'start',
    showPointer: true,
    switchWorkspaceTab: 'chat',
    interactiveAction: 'tab-change',
  },
  {
    element: '[data-tour="workspace-files-panel"]',
    title: 'Archivos y Repositorio Documental',
    description: 'Vincula carpetas en Google Drive o Dropbox y sube archivos con control de visibilidad.',
    actionHint: 'Administradores y trabajadores suben archivos; clientes pueden consultar y descargar.',
    side: 'left',
    align: 'start',
    showPointer: true,
    switchWorkspaceTab: 'chat',
  },
  {
    element: '[data-tour="workspace-timeline-panel"]',
    title: 'Trazabilidad y Linea de Tiempo',
    description: 'Historial cronologico de archivos compartidos, entregas completadas y cambios aprobados.',
    actionHint: 'Permite auditar cada avance y entrega del proyecto con fecha y responsable.',
    side: 'left',
    align: 'start',
    showPointer: true,
    switchWorkspaceTab: 'chat',
  },
  {
    element: '[data-tour="workspace-tab-brief"]',
    fallbackElement: '[data-tour="workspace-brief-content"]',
    title: 'Pestana Brief del Proyecto',
    description: 'Ficha tecnica con los requerimientos, especificaciones y alcance pactado.',
    actionHint: 'Haz clic para consultar las directrices y entregables acordados.',
    side: 'bottom',
    align: 'start',
    showPointer: true,
    switchWorkspaceTab: 'brief',
    interactiveAction: 'tab-change',
  },
]

export const CONTRACT_STEPS: CimaTourStep[] = [
  {
    element: '[data-tour="workspace-tab-contract"]',
    fallbackElement: '[data-tour="workspace-contract-content"]',
    title: 'Pestana Contratos y Enmiendas',
    description: 'Documento legal formal, terminos economicos y registro de firmas electronicas.',
    actionHint: 'Clientes y administradores pueden firmar aqui de forma segura.',
    side: 'bottom',
    align: 'start',
    showPointer: true,
    requiredRole: ['admin', 'client'],
    switchWorkspaceTab: 'contract',
    interactiveAction: 'tab-change',
  },
  {
    element: '[data-tour="workspace-contract-content"]',
    title: 'Lectura y Firma Digital',
    description: 'Permite leer el contrato completo, consultar anexos (Otro si) y plasmar la firma digital.',
    actionHint: 'Cuenta con plena validez juridica y trazabilidad de firma.',
    side: 'top',
    align: 'start',
    showPointer: true,
    requiredRole: ['admin', 'client'],
    switchWorkspaceTab: 'contract',
  },
]

export const CHANGE_STEPS: CimaTourStep[] = [
  {
    element: '[data-tour="workspace-tab-change-requests"]',
    fallbackElement: '[data-tour="workspace-change-requests-action"]',
    title: 'Pestana Solicitud de Cambios',
    description: 'Gestion formal de solicitudes de ajuste de alcance, tiempo o presupuesto (Otro si).',
    actionHint: 'Haz clic para revisar o formular solicitudes de cambio.',
    side: 'bottom',
    align: 'start',
    showPointer: true,
    switchWorkspaceTab: 'change-requests',
    interactiveAction: 'tab-change',
  },
  {
    element: '[data-tour="workspace-change-requests-action"]',
    title: 'Formulacion y Aprobacion de Cambios',
    description: 'Los clientes solicitan ajustes puntuales. Los administradores revisan y autorizan o rechazan.',
    actionHint: 'Evita desvios no autorizados en el alcance del proyecto.',
    side: 'bottom',
    align: 'start',
    showPointer: true,
    switchWorkspaceTab: 'change-requests',
  },
  {
    element: '[data-tour="workspace-tab-members"]',
    fallbackElement: '[data-tour="workspace-members-list"]',
    title: 'Pestana Integrantes del Proyecto',
    description: 'Lista del equipo de trabajo y representantes del cliente asignados al proyecto.',
    actionHint: 'Haz clic para ver el personal asignado y sus roles.',
    side: 'bottom',
    align: 'start',
    showPointer: true,
    switchWorkspaceTab: 'members',
    interactiveAction: 'tab-change',
  },
  {
    element: '[data-tour="workspace-members-list"]',
    title: 'Equipo Asignado',
    description: 'Consulta los miembros del equipo, sus especialidades y su ultima actividad.',
    actionHint: 'Muestra a todos los involucrados en el cumplimiento de los objetivos.',
    side: 'top',
    align: 'start',
    showPointer: true,
    switchWorkspaceTab: 'members',
  },
  {
    element: '[data-tour="workspace-back-btn"]',
    title: 'Volver a Proyectos',
    description: 'Regresa a la vista general del tablero Kanban de proyectos en cualquier momento.',
    actionHint: 'Haz clic para salir del espacio de trabajo del proyecto.',
    side: 'bottom',
    align: 'start',
    showPointer: true,
    interactiveAction: 'click',
  },
]

export const WORKSPACE_ALL_STEPS: CimaTourStep[] = [
  ...TASK_STEPS,
  ...DOC_STEPS,
  ...CONTRACT_STEPS,
  ...CHANGE_STEPS,
]
