import type { CimaTourStep } from '../model/types'

export const KANBAN_STEPS: CimaTourStep[] = [
  {
    element: '[data-tour="collab-search"]',
    scope: 'kanban',
    title: 'Buscador de Proyectos',
    description: 'Escribe el nombre del proyecto, cliente o correo para localizarlo al instante.',
    actionHint: 'Escribe para filtrar en tiempo real. Pulsa Siguiente cuando termines de explorar.',
    side: 'left',
  },
  {
    element: '[data-tour="collab-summary"]',
    scope: 'kanban',
    title: 'Resumen Rapido de Estados',
    description: 'Muestra el conteo de proyectos en cada etapa y el estado general de avance.',
    actionHint: 'Permite evaluar la carga de trabajo global en un solo vistazo.',
    side: 'bottom',
  },
  {
    element: '[data-tour="collab-columns-container"]',
    scope: 'kanban',
    fallbackElement: '[data-tour="collab-column-TODO"]',
    title: 'Columnas de Progreso Kanban',
    description: 'Los proyectos avanzan de izquierda a derecha: Por Iniciar, En Proceso, En Revision y Completado.',
    actionHint: 'Desliza horizontalmente en movil para explorar todas las columnas y sus proyectos.',
    side: 'top',
  },
  {
    element: '[data-tour="collab-create-btn"]',
    scope: 'kanban',
    title: 'Crear un Nuevo Proyecto',
    description: 'Permite registrar un nuevo proyecto asignando cliente, fechas y alcance acordado.',
    actionHint: 'Haz clic aqui para abrir el formulario de creacion o pulsa Siguiente.',
    side: 'left',
    requiredRole: ['admin'],
  },
  {
    element: '[data-tour="collab-card-first"]',
    scope: 'kanban',
    fallbackElement: '[data-tour="collab-columns-container"]',
    title: 'Abrir Espacio de Trabajo',
    description: 'Ingresa al espacio de trabajo completo para gestionar tareas, chat, brief y contratos.',
    emptyStateDescription:
      'Aun no tienes proyectos registrados. Explora las columnas o pulsa "Crear Proyecto" para iniciar tu primera entrega.',
    actionHint: 'Puedes abrir cualquier proyecto. Pulsa Siguiente para continuar el recorrido.',
    side: 'right',
  },
]

export const TASK_STEPS: CimaTourStep[] = [
  {
    element: '[data-tour="workspace-project-header"]',
    scope: 'workspace',
    title: 'Informacion del Proyecto',
    description: 'Muestra el nombre del proyecto, cliente asociado, fechas limite y estado de ejecucion.',
    actionHint: 'Consulta aqui el contexto clave antes de interactuar con las actividades.',
    side: 'bottom',
  },
  {
    element: '[data-tour="workspace-tab-board"]',
    scope: 'workspace',
    title: 'Pestana Tablero de Tareas',
    description: 'Visualiza el flujo de trabajo operativo organizado en columnas de estado.',
    actionHint: 'Haz clic para revisar las tareas y actividades asignadas.',
    side: 'bottom',
    switchWorkspaceTab: 'board',
  },
  {
    element: '[data-tour="workspace-task-columns"]',
    scope: 'workspace',
    title: 'Columnas del Flujo de Trabajo',
    description: 'Las tarjetas progresan desde la columna inicial hasta la entrega final aprobada.',
    actionHint: 'Desliza horizontalmente para ver todas las columnas. Pulsa una tarea para ver su detalle.',
    side: 'top',
    switchWorkspaceTab: 'board',
  },
  {
    element: '[data-tour="workspace-create-task-btn"]',
    scope: 'workspace',
    fallbackElement: '[data-tour="workspace-task-columns"]',
    title: 'Crear Nueva Tarea',
    description: 'Permite registrar nuevas tareas tecnicas, fijar fechas limite y asignar responsables.',
    emptyStateDescription:
      'Explora las columnas del flujo operativo o pulsa el boton mas para registrar tu primera actividad.',
    actionHint: 'Haz clic en el boton mas de la columna para agregar una actividad.',
    side: 'bottom',
    requiredRole: ['admin', 'worker'],
    switchWorkspaceTab: 'board',
  },
]

export const DOC_STEPS: CimaTourStep[] = [
  {
    element: '[data-tour="workspace-tab-chat"]',
    scope: 'workspace',
    fallbackElement: '[data-tour="workspace-chat-channels"]',
    title: 'Pestana Conversacion y Archivos',
    description: 'Canal de mensajeria en tiempo real y repositorio de archivos del proyecto.',
    actionHint: 'Haz clic para abrir los canales de comunicacion y la documentacion.',
    side: 'bottom',
    switchWorkspaceTab: 'chat',
  },
  {
    element: '[data-tour="workspace-files-panel"]',
    scope: 'workspace',
    title: 'Archivos y Repositorio Documental',
    description: 'Vincula carpetas en Google Drive o Dropbox y sube archivos con control de visibilidad.',
    actionHint: 'Administradores y trabajadores suben archivos; clientes pueden consultar y descargar.',
    side: 'left',
    switchWorkspaceTab: 'chat',
  },
  {
    element: '[data-tour="workspace-timeline-panel"]',
    scope: 'workspace',
    title: 'Trazabilidad y Linea de Tiempo',
    description: 'Historial cronologico de archivos compartidos, entregas completadas y cambios aprobados.',
    actionHint: 'Permite auditar cada avance y entrega del proyecto con fecha y responsable.',
    side: 'left',
    switchWorkspaceTab: 'chat',
  },
  {
    element: '[data-tour="workspace-tab-brief"]',
    scope: 'workspace',
    fallbackElement: '[data-tour="workspace-brief-content"]',
    title: 'Pestana Brief del Proyecto',
    description: 'Ficha tecnica con los requerimientos, especificaciones y alcance pactado.',
    actionHint: 'Haz clic para consultar las directrices y entregables acordados.',
    side: 'bottom',
    switchWorkspaceTab: 'brief',
  },
]

export const CONTRACT_STEPS: CimaTourStep[] = [
  {
    element: '[data-tour="workspace-tab-contract"]',
    scope: 'workspace',
    fallbackElement: '[data-tour="workspace-contract-content"]',
    title: 'Pestana Contratos y Enmiendas',
    description: 'Documento legal formal, terminos economicos y registro de firmas electronicas.',
    actionHint: 'Clientes y administradores pueden firmar aqui de forma segura.',
    side: 'bottom',
    requiredRole: ['admin', 'client'],
    switchWorkspaceTab: 'contract',
  },
  {
    element: '[data-tour="workspace-contract-content"]',
    scope: 'workspace',
    title: 'Lectura y Firma Digital',
    description: 'Permite leer el contrato completo, consultar anexos (Otro si) y plasmar la firma digital.',
    actionHint: 'Cuenta con plena validez juridica y trazabilidad de firma.',
    side: 'top',
    requiredRole: ['admin', 'client'],
    switchWorkspaceTab: 'contract',
  },
]

export const CHANGE_STEPS: CimaTourStep[] = [
  {
    element: '[data-tour="workspace-tab-change-requests"]',
    scope: 'workspace',
    fallbackElement: '[data-tour="workspace-change-requests-action"]',
    title: 'Pestana Solicitud de Cambios',
    description: 'Gestion formal de solicitudes de ajuste de alcance, tiempo o presupuesto (Otro si).',
    actionHint: 'Haz clic para revisar o formular solicitudes de cambio.',
    side: 'bottom',
    switchWorkspaceTab: 'change-requests',
  },
  {
    element: '[data-tour="workspace-change-requests-action"]',
    scope: 'workspace',
    title: 'Formulacion y Aprobacion de Cambios',
    description: 'Los clientes solicitan ajustes puntuales. Los administradores revisan y autorizan o rechazan.',
    actionHint: 'Evita desvios no autorizados en el alcance del proyecto.',
    side: 'bottom',
    switchWorkspaceTab: 'change-requests',
  },
  {
    element: '[data-tour="workspace-tab-members"]',
    scope: 'workspace',
    fallbackElement: '[data-tour="workspace-members-list"]',
    title: 'Pestana Integrantes del Proyecto',
    description: 'Lista del equipo de trabajo y representantes del cliente asignados al proyecto.',
    actionHint: 'Haz clic para ver el personal asignado y sus roles.',
    side: 'bottom',
    switchWorkspaceTab: 'members',
  },
  {
    element: '[data-tour="workspace-members-list"]',
    scope: 'workspace',
    title: 'Equipo Asignado',
    description: 'Consulta los miembros del equipo, sus especialidades y su ultima actividad.',
    actionHint: 'Muestra a todos los involucrados en el cumplimiento de los objetivos.',
    side: 'top',
    switchWorkspaceTab: 'members',
  },
  {
    element: '[data-tour="workspace-back-btn"]',
    scope: 'workspace',
    title: 'Volver a Proyectos',
    description: 'Regresa a la vista general del tablero Kanban de proyectos en cualquier momento.',
    actionHint: 'Haz clic para salir del espacio de trabajo del proyecto.',
    side: 'bottom',
  },
]

export const WORKSPACE_ALL_STEPS: CimaTourStep[] = [
  ...TASK_STEPS,
  ...DOC_STEPS,
  ...CONTRACT_STEPS,
  ...CHANGE_STEPS,
]

export const CLIENT_APPROVAL_STEPS: CimaTourStep[] = [
  {
    element: '[data-tour="workspace-tab-chat"]',
    scope: 'workspace',
    fallbackElement: '[data-tour="workspace-project-header"]',
    title: 'Pestaña Conversación y Archivos',
    description: 'Revisa entregables finales, documentos de diseño y recursos compartidos por el equipo.',
    actionHint: 'Haz clic para explorar los archivos del proyecto.',
    side: 'bottom',
    switchWorkspaceTab: 'chat',
  },
  {
    element: '[data-tour="workspace-files-panel"]',
    scope: 'workspace',
    title: 'Archivos y Repositorio de Entregables',
    description: 'Consulta y descarga los archivos aprobados para tu empresa con total seguridad y control.',
    actionHint: 'Pulsa sobre cualquier documento para descargarlo o previsualizarlo.',
    side: 'left',
    switchWorkspaceTab: 'chat',
  },
  {
    element: '[data-tour="workspace-tab-contract"]',
    scope: 'workspace',
    fallbackElement: '[data-tour="workspace-project-header"]',
    title: 'Pestaña Contratos y Enmiendas',
    description: 'Accede al documento legal formal, términos comerciales y registro de firmas vinculantes.',
    actionHint: 'Haz clic para revisar el contrato acordado.',
    side: 'bottom',
    requiredRole: ['client', 'admin'],
    switchWorkspaceTab: 'contract',
  },
  {
    element: '[data-tour="workspace-contract-content"]',
    scope: 'workspace',
    title: 'Lectura y Firma Digital Segura',
    description: 'Permite leer las cláusulas completas y estampar tu firma electrónica con plena validez jurídica.',
    actionHint: 'Revisa los términos y completa tu firma digital cuando estés conforme.',
    side: 'top',
    requiredRole: ['client', 'admin'],
    switchWorkspaceTab: 'contract',
  },
  {
    element: '[data-tour="workspace-tab-change-requests"]',
    scope: 'workspace',
    fallbackElement: '[data-tour="workspace-project-header"]',
    title: 'Pestaña Solicitud de Cambios',
    description: 'Canal oficial para solicitar modificaciones de alcance, entregables adicionales o ajustes de cronograma.',
    actionHint: 'Haz clic para gestionar solicitudes formales de ajuste.',
    side: 'bottom',
    switchWorkspaceTab: 'change-requests',
  },
  {
    element: '[data-tour="workspace-change-requests-action"]',
    scope: 'workspace',
    title: 'Formular un Ajuste de Alcance',
    description: 'Describe el ajuste requerido para que el equipo directivo evalúe su viabilidad y emita el Otro sí.',
    actionHint: 'Envía tu petición formal para mantener la gobernanza ordenada de tu proyecto.',
    side: 'bottom',
    switchWorkspaceTab: 'change-requests',
  },
]
