import type { CimaTourDefinition, GuidedQuestion } from '../model/types'

export const marketingTour: CimaTourDefinition = {
  id: 'tour-marketing',
  tab: 'marketing',
  title: 'Recorrido del Módulo de Marketing',
  description: 'Conoce cómo gestionar tus campañas, propuestas comerciales y automatizaciones de clientes.',
  roles: ['admin', 'worker'],
  steps: [
    {
      element: '[data-tour="marketing-header"]',
      title: 'Estrategia y Crecimiento',
      description: 'Panel de control principal para supervisar la ejecución de campañas de marketing y relaciones comerciales.',
      actionHint: 'Consulta este encabezado para verificar el módulo activo.',
      side: 'bottom',
      align: 'start',
      showPointer: true,
    },
    {
      element: '[data-tour="marketing-tabs"]',
      title: 'Secciones Estratégicas',
      description: 'Alterna ágilmente entre Clientes, Campañas, Propuestas, Automatizaciones, Segmentos e Interacciones.',
      actionHint: 'Haz clic en cualquier pestaña para ver su detalle operativo.',
      side: 'bottom',
      align: 'center',
      showPointer: true,
    },
    {
      element: '[data-tour="marketing-clients-plans-grid"]',
      switchWorkspaceTab: 'clients',
      fallbackElement: '[data-tour="marketing-tabs"]',
      title: 'Clasificación de Clientes y Planes',
      description: 'Supervisa la cartera clasificada en planes Oro, Esmeralda y Premium para priorizar la atención.',
      actionHint: 'Examina la distribución y el porcentaje de clientes en cada plan.',
      side: 'bottom',
      align: 'center',
      showPointer: true,
    },
    {
      element: '[data-tour="marketing-clients-sync-btn"]',
      switchWorkspaceTab: 'clients',
      fallbackElement: '[data-tour="marketing-tabs"]',
      title: 'Sincronización con el CRM',
      description: 'Importa y sincroniza al instante clientes y proyectos registrados desde la base comercial central.',
      actionHint: 'Pulsa el botón para sincronizar los datos más recientes del CRM.',
      side: 'bottom',
      align: 'end',
      showPointer: true,
    },
    {
      element: '[data-tour="marketing-new-campaign-btn"]',
      switchWorkspaceTab: 'campaigns',
      fallbackElement: '[data-tour="marketing-tabs"]',
      title: 'Crear una Campaña',
      description: 'Inicia el asistente para redactar, segmentar y programar un nuevo lanzamiento o difusión comercial.',
      actionHint: 'Pulsa Nueva Campaña para abrir el formulario de configuración.',
      side: 'bottom',
      align: 'end',
      showPointer: true,
    },
    {
      element: '[data-tour="marketing-campaigns-filters"]',
      switchWorkspaceTab: 'campaigns',
      fallbackElement: '[data-tour="marketing-tabs"]',
      title: 'Filtros y Búsqueda de Campañas',
      description: 'Localiza campañas filtrando por estado operativo, tipología o búsqueda en tiempo real.',
      actionHint: 'Filtra por campañas activas, planificadas o completadas según tu necesidad.',
      side: 'bottom',
      align: 'start',
      showPointer: true,
    },
    {
      element: '[data-tour="marketing-new-proposal-btn"]',
      switchWorkspaceTab: 'proposals',
      fallbackElement: '[data-tour="marketing-tabs"]',
      title: 'Registro de Propuestas Comerciales',
      description: 'Presenta cotizaciones y proyectos con montos estimados, fechas límite y seguimiento de respuestas.',
      actionHint: 'Haz clic en Nueva Propuesta para registrar una oferta a un cliente.',
      side: 'bottom',
      align: 'end',
      showPointer: true,
    },
    {
      element: '[data-tour="marketing-new-workflow-btn"]',
      switchWorkspaceTab: 'workflows',
      fallbackElement: '[data-tour="marketing-tabs"]',
      title: 'Flujos Automatizados',
      description: 'Programa automatizaciones para reaccionar ante inactividad, enviar recordatorios y fidelizar clientes.',
      actionHint: 'Pulsa Nueva Automatización para diseñar un flujo inteligente.',
      side: 'bottom',
      align: 'end',
      showPointer: true,
    },
  ],
}

export const marketingQuestions: GuidedQuestion[] = [
  {
    id: 'mkt-q1',
    question: '¿Cómo creo una nueva campaña publicitaria?',
    answer: 'En la sección de Campañas, haz clic en el botón superior "+ Nueva Campaña", asigna el nombre, objetivo y fechas.',
    tab: 'marketing',
    roles: ['admin', 'worker'],
    category: 'gestion',
    targetElement: '[data-tour="marketing-new-campaign-btn"]',
    fallbackTargetElement: '[data-tour="marketing-tabs"]',
  },
  {
    id: 'mkt-q2',
    question: '¿Dónde puedo ver el resumen de crecimiento de marketing?',
    answer: 'En el encabezado de Marketing y en las tarjetas consolidadas dispones del panorama general de actividad.',
    tab: 'marketing',
    roles: ['admin', 'worker'],
    category: 'flujo',
    targetElement: '[data-tour="marketing-header"]',
  },
  {
    id: 'mkt-q3',
    question: '¿Cómo alterno entre clientes, propuestas y automatizaciones?',
    answer: 'Utiliza la barra de pestañas para acceder a Clientes, Campañas, Propuestas, Automatizaciones, Segmentos e Interacciones.',
    tab: 'marketing',
    roles: ['admin', 'worker'],
    category: 'flujo',
    targetElement: '[data-tour="marketing-tabs"]',
  },
  {
    id: 'mkt-q4',
    question: '¿Cómo sincronizo los clientes con el CRM comercial?',
    answer: 'En la pestaña Clientes, pulsa el botón "Sincronizar con el CRM" para traer los datos más recientes del sistema central.',
    tab: 'marketing',
    roles: ['admin', 'worker'],
    category: 'gestion',
    targetElement: '[data-tour="marketing-clients-sync-btn"]',
    fallbackTargetElement: '[data-tour="marketing-tabs"]',
  },
  {
    id: 'mkt-q5',
    question: '¿Dónde consulto la distribución de planes de mi cartera?',
    answer: 'En la sección Clientes encontrarás las tarjetas resumen de planes Oro, Esmeralda, Premium y los pendientes de clasificar.',
    tab: 'marketing',
    roles: ['admin', 'worker'],
    category: 'gestion',
    targetElement: '[data-tour="marketing-clients-plans-grid"]',
    fallbackTargetElement: '[data-tour="marketing-tabs"]',
  },
  {
    id: 'mkt-q6',
    question: '¿Cómo registro una nueva propuesta comercial?',
    answer: 'Accede a la pestaña Propuestas y presiona "+ Nueva Propuesta" indicando cliente, monto estimado y alcance.',
    tab: 'marketing',
    roles: ['admin', 'worker'],
    category: 'gestion',
    targetElement: '[data-tour="marketing-new-proposal-btn"]',
    fallbackTargetElement: '[data-tour="marketing-tabs"]',
  },
  {
    id: 'mkt-q7',
    question: '¿Cómo configuro un flujo de automatización?',
    answer: 'Ingresa a la sección Automatizaciones y haz clic en "+ Nueva Automatización" vinculándola a una campaña.',
    tab: 'marketing',
    roles: ['admin', 'worker'],
    category: 'gestion',
    targetElement: '[data-tour="marketing-new-workflow-btn"]',
    fallbackTargetElement: '[data-tour="marketing-tabs"]',
  },
]
