import type { CimaTourDefinition, GuidedQuestion } from '../model/types'

export const overviewTour: CimaTourDefinition = {
  id: 'tour-overview',
  tab: 'overview',
  title: 'Recorrido de la Pestaña Resumen',
  description: 'Conoce los indicadores clave, tareas prioritarias y accesos directos de tu panel principal.',
  roles: ['admin', 'worker'],
  steps: [
    {
      element: '[data-tour="overview-identity"]',
      title: 'Identidad y Perfil',
      description: 'Muestra tu información de usuario, correo corporativo, rol activo y la fecha de la jornada.',
      actionHint: 'Verifica que tu sesión y rol correspondan con tus actividades de trabajo.',
      side: 'bottom',
      align: 'start',
      showPointer: true,
    },
    {
      element: '[data-tour="overview-notifications"]',
      title: 'Avisos y Novedades del Sistema',
      description: 'Alertas prioritarias, menciones y actualizaciones importantes sobre proyectos y tareas.',
      actionHint: 'Pulsa sobre cualquier notificación para consultar su detalle inmediato.',
      side: 'bottom',
      align: 'center',
      showPointer: true,
    },
    {
      element: '[data-tour="overview-kpis"]',
      title: 'Indicadores Clave de Desempeño',
      description: 'Métricas consolidadas de proyectos activos, avance de metas y actividad global.',
      actionHint: 'Revisa estos números para evaluar el ritmo operativo y cumplimiento general.',
      side: 'bottom',
      align: 'center',
      showPointer: true,
    },
    {
      element: '[data-tour="overview-worker-tasks"]',
      title: 'Mis Tareas Pendientes',
      description: 'Listado de tareas asignadas a tu cuenta que requieren entrega o están en progreso.',
      actionHint: 'Pulsa en la tarea o en el acceso al proyecto para abrir el tablero de trabajo.',
      side: 'top',
      align: 'start',
      showPointer: true,
      requiredRole: ['worker'],
    },
    {
      element: '[data-tour="overview-admin-changes"]',
      title: 'Solicitudes de Cambio Pendientes',
      description: 'Peticiones de ajuste o alcance solicitadas por los clientes que esperan tu revisión.',
      actionHint: 'Pulsa sobre una solicitud para analizar su impacto y gestionarla de inmediato.',
      side: 'top',
      align: 'start',
      showPointer: true,
      requiredRole: ['admin'],
    },
    {
      element: '[data-tour="overview-admin-blocked"]',
      title: 'Tareas Bloqueadas para Atención',
      description: 'Tareas con impedimentos técnicos, cuellos de botella o dependencias pendientes.',
      actionHint: 'Examina el bloqueo para coordinar su resolución con el equipo responsable.',
      side: 'top',
      align: 'start',
      showPointer: true,
      requiredRole: ['admin'],
    },
    {
      element: '[data-tour="overview-recent-projects"]',
      title: 'Proyectos con Actividad Reciente',
      description: 'Acceso directo a los proyectos con actualizaciones recientes y su porcentaje de avance.',
      actionHint: 'Haz clic en cualquier proyecto para abrir directamente su espacio de trabajo.',
      side: 'top',
      align: 'start',
      showPointer: true,
      requiredRole: ['admin'],
    },
    {
      element: '[data-tour="overview-admin-clients"]',
      title: 'Directorio de Clientes Recientes',
      description: 'Nuevas cuentas de clientes registradas en el CRM listas para seguimiento comercial.',
      actionHint: 'Consulta el estado de cada cliente para coordinar el contacto inicial.',
      side: 'top',
      align: 'start',
      showPointer: true,
      requiredRole: ['admin'],
    },
    {
      element: '[data-tour="overview-admin-workload"]',
      title: 'Distribución de Carga de Trabajo',
      description: 'Monitoreo del volumen de tareas asignadas por colaborador para balancear el esfuerzo.',
      actionHint: 'Identifica colaboradores con disponibilidad para equilibrar nuevas asignaciones.',
      side: 'top',
      align: 'start',
      showPointer: true,
      requiredRole: ['admin'],
    },
    {
      element: '[data-tour="overview-admin-ranking"]',
      title: 'Ranking y Actividad de Clientes',
      description: 'Clasificación de cuentas según su volumen de proyectos y participación en el CRM.',
      actionHint: 'Usa esta métrica para priorizar la atención a las cuentas más estratégicas.',
      side: 'top',
      align: 'start',
      showPointer: true,
      requiredRole: ['admin'],
    },
  ],
}

export const overviewQuestions: GuidedQuestion[] = [
  {
    id: 'ov-q-overview',
    question: '¿Qué información resume la pantalla de Resumen?',
    answer: 'Presenta una vista panorámica con tus accesos directos, notificaciones, indicadores y tareas prioritarias.',
    tab: 'overview',
    roles: ['admin', 'worker'],
    category: 'flujo',
    tourId: 'tour-overview',
  },
  {
    id: 'ov-q-identity',
    question: '¿Dónde verifico mi usuario, rol y fecha de trabajo?',
    answer: 'En el encabezado superior se muestran tu nombre, correo corporativo, rol activo y la fecha de hoy.',
    tab: 'overview',
    roles: ['admin', 'worker'],
    category: 'gestion',
    targetElement: '[data-tour="overview-identity"]',
  },
  {
    id: 'ov-q-notifications',
    question: '¿Dónde reviso mis avisos urgentes y notificaciones?',
    answer: 'En la sección de Avisos del Sistema encuentras las alertas y cambios recientes en proyectos.',
    tab: 'overview',
    roles: ['admin', 'worker'],
    category: 'comunicacion',
    targetElement: '[data-tour="overview-notifications"]',
  },
  {
    id: 'ov-q-kpis',
    question: '¿Cómo interpreto los indicadores clave de desempeño?',
    answer: 'Las tarjetas de KPIs sintetizan los proyectos activos, nivel de avance y actividad comercial.',
    tab: 'overview',
    roles: ['admin', 'worker'],
    category: 'flujo',
    targetElement: '[data-tour="overview-kpis"]',
  },
  {
    id: 'ov-q-worker-tasks',
    question: '¿Dónde consulto las tareas que tengo asignadas para hoy?',
    answer: 'En Mis Tareas Pendientes visualizas tus entregas inmediatas y el acceso directo al tablero Kanban.',
    tab: 'overview',
    roles: ['worker'],
    category: 'gestion',
    targetElement: '[data-tour="overview-worker-tasks"]',
  },
  {
    id: 'ov-q-admin-changes',
    question: '¿Dónde reviso o apruebo solicitudes de cambio de clientes?',
    answer: 'En la sección Solicitudes de Cambio puedes auditar las peticiones recibidas y gestionarlas oportunamente.',
    tab: 'overview',
    roles: ['admin'],
    category: 'gestion',
    targetElement: '[data-tour="overview-admin-changes"]',
  },
  {
    id: 'ov-q-admin-blocked',
    question: '¿Qué debo hacer si una tarea se encuentra bloqueada?',
    answer: 'En Tareas Bloqueadas identificas los cuellos de botella para intervenir y reanudar el flujo de trabajo.',
    tab: 'overview',
    roles: ['admin'],
    category: 'gestion',
    targetElement: '[data-tour="overview-admin-blocked"]',
  },
  {
    id: 'ov-q-recent-projects',
    question: '¿Cómo accedo directamente a un proyecto reciente?',
    answer: 'En Proyectos Recientes haz clic en la tarjeta del proyecto para abrir directamente su espacio colaborativo.',
    tab: 'overview',
    roles: ['admin'],
    category: 'flujo',
    targetElement: '[data-tour="overview-recent-projects"]',
  },
  {
    id: 'ov-q-admin-clients',
    question: '¿Dónde consulto los clientes registrados recientemente?',
    answer: 'En Clientes Recientes se lista el directorio con las últimas empresas incorporadas al CRM.',
    tab: 'overview',
    roles: ['admin'],
    category: 'gestion',
    targetElement: '[data-tour="overview-admin-clients"]',
  },
  {
    id: 'ov-q-admin-workload',
    question: '¿Cómo superviso la carga de trabajo entre colaboradores?',
    answer: 'El panel de Carga de Trabajo indica el volumen de tareas de cada colaborador para balancear responsabilidades.',
    tab: 'overview',
    roles: ['admin'],
    category: 'gestion',
    targetElement: '[data-tour="overview-admin-workload"]',
  },
  {
    id: 'ov-q-admin-ranking',
    question: '¿Cómo identifico a los clientes con mayor participación?',
    answer: 'En Ranking de Clientes se muestran las cuentas ordenadas por actividad y volumen de proyectos.',
    tab: 'overview',
    roles: ['admin'],
    category: 'flujo',
    targetElement: '[data-tour="overview-admin-ranking"]',
  },
]
