name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

concurrency:
  group: ci-frontend-${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate:
    uses: SebasCarvajal11/crm-infra/.github/workflows/reusable-ci.yml@v2.1.0
    with:
      component: frontend
      is_frontend: true
      test_command: echo "No unit tests for frontend"
    secrets: inherit
